import { ICON_AID } from "@/generated/icons-enum";
import { LeftSignature, RightSignature } from "@/constants";
import type { RulesGroup } from "@/types";
import { ICON_CATEGORIES } from "@/generated/icon-categories-enum";
export const AID_RULES_GROUP = {
    category: ICON_CATEGORIES.Aid,
    rules: [
        {
            order: 0,
            prefix: [ICON_AID.Lunchbox],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|lunchbox"],
            exclude: [],
        },
        {
            order: 1,
            prefix: [ICON_AID.Scout],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|Banner_Consumable"],
            exclude: [],
        },
        {
            order: 2,
            prefix: [ICON_AID.TreasureHuntChest],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|TreasureHunt_Chest"],
            exclude: [],
        },
        {
            order: 3,
            prefix: [ICON_AID.HolidayGift],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|HolidayGift"],
            exclude: [],
        },
        {
            order: 4,
            prefix: [ICON_AID.Stimpak],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "edid|SURV_DiseaseCure_HerbalMedicine",
                "edid|SURV_DiseaseCure_Antibiotics",
                "edid|InsectRepellent",
                "edid|Stimpak",
                "edid|StimpakDiluted",
                "edid|SuperStimpak",
                "edid|StimGas",
                "edid|ResuscitationKit",
                "edid|medx",
                "edid|calmex",
                "edid|FormulaP",
                "edid|FormulaB",
                "edid|FormulaQ",
                "edid|Addictol",
                "edid|HealingSalve",
            ],
            exclude: [
                "edid|VenisonAndTatoStew_Stimpak"
            ],
        },
        {
            order: 5,
            prefix: [ICON_AID.Radaway],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "edid|radaway",
                "edid|Radx",
                "edid|RadShield",
                "edid|Radiation_RadXtreme",
                "edid|TrenchMed_Pitt",
            ],
            exclude: [],
        },
        {
            order: 6,
            prefix: [ICON_AID.Drugs],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "edid|mentats",
                "edid|buffout",
                "edid|bufftats",
                "edid|Psycho",
                "edid|Overdrive",
                "edid|ChemBlend",
                "edid|Fury",
                "edid|SurvivalShortcut",
                "edid|BrawlingChemist",
                "edid|DaddyO",
                "edid|DayTripper",
                "edid|XCell",
                "edid|GHL_TheFix",
                "edid|SkeetoSpit"
            ],
            exclude: [],
        },
        {
            order: 7,
            prefix: [ICON_AID.Stealthboy],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|stealth"],
            exclude: [],
        },
        {
            order: 8,
            prefix: [ICON_AID.BloodPack],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "edid|Bloodpack",
                "edid|BloodpackIrradiated",
                "edid|GlowingOneBlood",
                "edid|BloodpackGlowing"
            ],
            exclude: [],
        },
        {
            order: 9,
            prefix: [ICON_AID.MutationSerum],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|ObjectTypeSerum"],
            exclude: [],
        },
        {
            order: 10,
            prefix: [ICON_AID.FluxAid],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|FloraSpecimen"],
            exclude: [],
        },
        {
            order: 11,
            prefix: [ICON_AID.MysteryBox],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "edid|SCORE_BobbleheadBox",
                "edid|SCORE_MagazineBookBox"
            ],
            exclude: [],
        },
        {
            order: 12,
            prefix: [ICON_AID.Magazine],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|MagazineKeyword"],
            exclude: [],
        },
        {
            order: 13,
            prefix: [ICON_AID.Bobblehead],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|BobbleheadKeyword"],
            exclude: [],
        }
    ],
} as const satisfies RulesGroup<ICON_AID>;
