import { ICON_AID } from '@/generated/icons-enum';
import { LeftSignature, RightSignature } from '@/constants';
import type { RulesGroup } from '@/types';
import { ICON_CATEGORIES } from '@/generated/icon-categories-enum';

export const AID_RULES_GROUP = {
  category: ICON_CATEGORIES.Aid,
  rules: [
    {
      order: 0,
      prefix: [ICON_AID.Lunchbox],
      leftSignature: LeftSignature.Alchemy,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x22be',
      include: ['edid|lunchbox'],
      exclude: [],
    },
    {
      order: 1,
      prefix: [ICON_AID.Scout],
      leftSignature: LeftSignature.Alchemy,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x22bf',
      include: ['edid|Banner_Consumable'],
      exclude: [],
    },
    {
      order: 2,
      prefix: [ICON_AID.TreasureHuntChest],
      leftSignature: LeftSignature.Alchemy,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x22c0',
      include: ['edid|TreasureHunt_Chest'],
      exclude: [],
    },
    {
      order: 3,
      prefix: [ICON_AID.HolidayGift],
      leftSignature: LeftSignature.Alchemy,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x22c1',
      include: ['edid|HolidayGift'],
      exclude: [],
    },
    {
      order: 4,
      prefix: [ICON_AID.Antibiotics],
      leftSignature: LeftSignature.Alchemy,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: true,
      isFullReplaced: false,
      header: '0x22c2',
      include: [
        'edid|SURV_DiseaseCure_HerbalMedicine',
        'edid|SURV_DiseaseCure_Antibiotics',
      ],
      exclude: [],
    },
    {
      order: 5,
      prefix: [ICON_AID.Stimpak],
      leftSignature: LeftSignature.Alchemy,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x22c3',
      include: ['ekwd|ObjectTypeStimpak'],
      exclude: [],
    },
    {
      order: 6,
      prefix: [ICON_AID.Radaway],
      leftSignature: LeftSignature.Alchemy,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x22c4',
      include: ['ekwd|ObjectTypeChem', 'ekwd|ChemTypeRadaway'],
      exclude: [],
    },
    {
      order: 7,
      prefix: [ICON_AID.RadX],
      leftSignature: LeftSignature.Alchemy,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: true,
      isFullReplaced: false,
      header: '0x22c5',
      include: [
        'edid|Radx',
        'edid|RadShield',
        'edid|Radiation_RadXtreme',
        'edid|TrenchMed_Pitt',
      ],
      exclude: [],
    },
    {
      order: 8,
      prefix: [ICON_AID.MedX],
      leftSignature: LeftSignature.Alchemy,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: true,
      isFullReplaced: false,
      header: '0x22c6',
      include: [
        'edid|medx',
        'edid|calmex',
        'edid|FormulaP',
        'edid|FormulaB',
        'edid|FormulaQ',
      ],
      exclude: [],
    },
    {
      order: 9,
      prefix: [ICON_AID.Stealthboy],
      leftSignature: LeftSignature.Alchemy,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x22c7',
      include: ['edid|stealth'],
      exclude: [],
    },
    {
      order: 10,
      prefix: [ICON_AID.Addictol],
      leftSignature: LeftSignature.Alchemy,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x22c8',
      include: ['edid|Addictol'],
      exclude: [],
    },
    {
      order: 11,
      prefix: [ICON_AID.BloodPack],
      leftSignature: LeftSignature.Alchemy,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: true,
      isFullReplaced: false,
      header: '0x22c9',
      include: ['edid|Bloodpack', 'edid|BloodpackIrradiated'],
      exclude: ['edid|GlowingOneBlood', 'edid|BloodpackGlowing'],
    },
    {
      order: 12,
      prefix: [ICON_AID.GlowingBlood],
      leftSignature: LeftSignature.Alchemy,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: true,
      isFullReplaced: false,
      header: '0x22ca',
      include: ['edid|GlowingOneBlood', 'edid|BloodpackGlowing'],
      exclude: [],
    },
    {
      order: 13,
      prefix: [ICON_AID.XCell],
      leftSignature: LeftSignature.Alchemy,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x22cb',
      include: ['edid|XCell'],
      exclude: [],
    },
    {
      order: 14,
      prefix: [ICON_AID.Mentats],
      leftSignature: LeftSignature.Alchemy,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x22cc',
      include: ['ekwd|AddictionKeywordMentats'],
      exclude: [],
    },
    {
      order: 15,
      prefix: [ICON_AID.Buffout],
      leftSignature: LeftSignature.Alchemy,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: true,
      isFullReplaced: false,
      header: '0x22cd',
      include: ['edid|Buffout', 'edid|Bufftats'],
      exclude: [],
    },
    {
      order: 16,
      prefix: [ICON_AID.Psycho],
      leftSignature: LeftSignature.Alchemy,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: true,
      isFullReplaced: false,
      header: '0x22ce',
      include: [
        'edid|Psycho',
        'edid|Overdrive',
        'edid|ChemBlend',
        'edid|Fury',
        'edid|SurvivalShortcut',
        'edid|BrawlingChemist',
        'edid|DaddyO',
      ],
      exclude: ['edid|VenisonAndTatoStew_Psycho'],
    },
    {
      order: 17,
      prefix: [ICON_AID.MutationSerum],
      leftSignature: LeftSignature.Alchemy,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x22cf',
      include: ['ekwd|ObjectTypeSerum'],
      exclude: [],
    },
    {
      order: 18,
      prefix: [ICON_AID.DayTripper],
      leftSignature: LeftSignature.Alchemy,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x22d0',
      include: ['edid|DayTripper'],
      exclude: [],
    },
    {
      order: 19,
      prefix: [ICON_AID.Magazine],
      leftSignature: LeftSignature.Alchemy,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: true,
      isFullReplaced: false,
      header: '0x22d1',
      include: ['ekwd|MagazineKeyword'],
      exclude: [],
    },
    {
      order: 20,
      prefix: [ICON_AID.Bobblehead],
      leftSignature: LeftSignature.Alchemy,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x22d2',
      include: ['ekwd|BobbleheadKeyword'],
      exclude: [],
    },
  ],
} as const satisfies RulesGroup<ICON_AID>;
