import { ICON_AMMO } from "@/generated/icons-enum";
import { LeftSignature, RightSignature } from "@/constants";
import type { RulesGroup } from "@/types";
import { ICON_CATEGORIES } from "@/generated/icon-categories-enum";
const fusionCellInclude = [
    "ekwd|AmmoTypeEnergy"
] as const;
const nukaColaInclude = [
    "edid|quantum",
    "edid|cherry",
    "edid|NukaCola",
    "edid|Ammo_ThirstZapperWater"
] as const;
const grenadeLauncherInclude = [
    "edid|AmmoGrenadeLauncher"
] as const;
export const AMMO_RULES_GROUP = {
    category: ICON_CATEGORIES.Ammo,
    rules: [
        {
            order: 0,
            prefix: [ICON_AMMO.MiniNuke],
            leftSignature: LeftSignature.Ammunition,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: ["edid|FatManMiniNuke", "edid|NukaNuke"],
            exclude: [],
        },
        {
            order: 1,
            prefix: [ICON_AMMO.FusionCore],
            leftSignature: LeftSignature.Ammunition,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: ["edid|FusionCore", "edid|PlasmaCore"],
            exclude: [],
        },
        {
            order: 2,
            prefix: [ICON_AMMO.Rocket],
            leftSignature: LeftSignature.Ammunition,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: ["edid|AmmoMissile", "edid|AmmoSentryShoulder"],
            exclude: [],
        },
        {
            order: 3,
            prefix: [ICON_AMMO.FortyMmGrenade],
            leftSignature: LeftSignature.Ammunition,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [...grenadeLauncherInclude],
            exclude: [],
        },
        {
            order: 4,
            prefix: [ICON_AMMO.Fuel],
            leftSignature: LeftSignature.Ammunition,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|fuel"],
            exclude: [],
        },
        {
            order: 5,
            prefix: [ICON_AMMO.FusionCell],
            leftSignature: LeftSignature.Ammunition,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [...fusionCellInclude],
            exclude: [
                "edid|AmmoFlamerFuel",
                "edid|AmmoBlueFlamerFuel",
                "edid|AmmoPlasmaCore",
                "edid|AmmoPlasmaCore_AntiScorched",
                "edid|AmmoFusionCore_AntiScorchBeast",
                "edid|AmmoFusionCore"
            ],
        },
        {
            order: 6,
            prefix: [ICON_AMMO.NukaColaAmmo],
            leftSignature: LeftSignature.Ammunition,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [...nukaColaInclude],
            exclude: [],
        },
        {
            order: 7,
            prefix: [ICON_AMMO.Arrows],
            leftSignature: LeftSignature.Ammunition,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: ["edid|arrow", "edid|CrossbowBolt"],
            exclude: [],
        },
        {
            order: 8,
            prefix: [ICON_AMMO.CameraFilm],
            leftSignature: LeftSignature.Ammunition,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|AmmoCamera"],
            exclude: [],
        },
        {
            order: 9,
            prefix: [ICON_AMMO.BallisticAmmo],
            leftSignature: LeftSignature.Ammunition,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|ObjectTypeAmmo"],
            exclude: [
                ...fusionCellInclude,
                ...nukaColaInclude,
                ...grenadeLauncherInclude,
                "edid|FatManMiniNuke",
                "ekwd|AmmoTypeFusionCore",
                "edid|fuel",
            ],
        }
    ],
} as const satisfies RulesGroup<ICON_AMMO>;
