import { ICON_APPAREL } from "@/generated/icons-enum";
import { LeftSignature, RightSignature } from "@/constants";
import type { IncludeProperty, RulesGroup } from "@/types";
import { ICON_CATEGORIES } from "@/generated/icon-categories-enum";
const flowerCrownRules = [
    "edid|FlowerCrown"
] as const satisfies IncludeProperty[];
const capInclude: IncludeProperty[] = [
    "edid|SCORE_S11_ARMO_Headwear_SodaJerkCap",
    "edid|ATX_Headwear_MilitaryUtilityCap_Green",
    "edid|ATX_Headwear_MilitaryUtilityCap_Camo",
    "edid|XPD_AC_Headwear_Buttercup",
    "edid|Headwear_Resident7Hat",
    "edid|ATX_Headwear_PiperCap_SP1",
    "edid|Headwear_Raider_Hood",
    "edid|ATX_Headwear_LeatherCap",
    "edid|ATX_Headwear_MilitaryUtilityCap_Tan"
];
const fedoraInclude: IncludeProperty[] = [
    "edid|headwear",
    "edid|Encryptid_Clothes_WhiteFedora",
    "edid|Mini_Robot_Hat",
    "edid|Tadpole_Clothes_PioneerScoutOutfit_Squirrel_Skirt",
    "edid|Supermutant_KingGrognak_Headband",
    "edid|Herd_Workshop_Clothes_BlueDevilHooddd"
];
const helmetInclude: IncludeProperty[] = [
    "edid|helmet",
    "edid|SupermutantHat",
    "edid|Supermutant76Hat1",
    "edid|ATX_Headwear_VintageFootball",
    "edid|Headwear_ChineseStealthArmor",
    "edid|Headwear_PumpkinHeavy_Black",
    "edid|Headwear_SpaceSuitHatClean",
    "edid|Headwear_AlaskanWinter",
    "edid|Headwear_CaptainCosmos",
    "edid|Creature_Spooky_Headwear_CaptainCosmos",
    "edid|Headwear_FreeStatesResistance",
    "edid|Headwear_PumpkinHeavy",
    "edid|Spooky_Headwear_PumpkinHeavy",
    "edid|F1_Headwear_RangersUniform",
    "edid|Headwear_HalloweenVikingBustedHorns",
    "edid|Spooky_Headwear_HalloweenVikingBustedHorns",
    "edid|Headwear_SkullRider_Flaming",
    "edid|Headwear_SkullRider_Rad",
    "edid|Armor_Raider_Skilanes_Headwear",
    "edid|Headwear_SkullRider",
    "edid|Headwear_CardboardRobot",
    "edid|Headwear_Responders_FirebreatherHat",
    "edid|Headwear_DeathclawMascot",
    "edid|Headwear_CommunistSpaceSuit",
    "edid|Headwear_FiremanHat",
    "edid|Headwear_Clothes_DLC03_Marine_Arctic",
    "edid|Headwear_FreeStatesRevolutionary",
    "edid|Headwear_BloodEagleMerc_Charmer2",
    "edid|Headwear_BloodEagleMerc_Charmer1",
    "edid|Headwear_SpaceSuitHat",
    "edid|Headwear_Union",
    "edid|Headwear_Responders_FiremanHat",
    "edid|Headwear_SuperMutant_Helm",
    "edid|Headwear_MutantArmor",
    "edid|Headwear_RangerArmor_Desert",
    "edid|Headwear_RangerArmor_Riot",
    "edid|Headwear_Clothes_Tempest"
];
const beretInclude: IncludeProperty[] = [
    "edid|beret",
    "edid|MilitaryCap",
    "edid|DLC03CaptainsDanceHat"
];
const gasMaskInclude: IncludeProperty[] = [
    "edid|gasmask",
    "edid|Headwear_Radicals_Mask_A"
];
const fasnachtMaskKeywordInclude: IncludeProperty[] = [
    "ekwd|fasnacht"
];
const fasnachtMaskEdidInclude: IncludeProperty[] = [
    "edid|Veteran_Mask",
    "edid|ClothesMistressOfMysteryVeil",
    "edid|ClothesMistressOfMysteryWornVeil"
];
export const APPAREL_RULES_GROUP = {
    category: ICON_CATEGORIES.Apparel,
    rules: [
        {
            order: 0,
            prefix: [ICON_APPAREL.Glasses],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|ClothingTypeGlasses"],
            exclude: [],
        },
        {
            order: 1,
            prefix: [ICON_APPAREL.FasnachtMask],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: fasnachtMaskKeywordInclude,
            exclude: [],
        },
        {
            order: 2,
            prefix: [ICON_APPAREL.FasnachtMask],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: fasnachtMaskEdidInclude,
            exclude: [],
        },
        {
            order: 3,
            prefix: [ICON_APPAREL.FlowerCrown],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [...flowerCrownRules],
            exclude: [],
        },
        {
            order: 4,
            prefix: [ICON_APPAREL.SpacesuitHat],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|Headwear_Jumpsuit_SpaceSuit"],
            exclude: [],
        },
        {
            order: 5,
            prefix: [ICON_APPAREL.SpacesuitHat],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [
                "ekwd|ClothingTypeHat",
                "ekwd|ClothingTypeSpaceSuit"
            ],
            exclude: [],
        },
        {
            order: 6,
            prefix: [ICON_APPAREL.CowboyHat],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|HatTypeCowboy"],
            exclude: [],
        },
        {
            order: 7,
            prefix: [ICON_APPAREL.CowboyHat],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|Veracio_Hat"],
            exclude: [],
        },
        {
            order: 8,
            prefix: [ICON_APPAREL.Cap],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: capInclude,
            exclude: [],
        },
        {
            order: 9,
            prefix: [ICON_APPAREL.Beret],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: beretInclude,
            exclude: [
                ...fasnachtMaskKeywordInclude,
                ...fasnachtMaskEdidInclude,
            ],
        },
        {
            order: 10,
            prefix: [ICON_APPAREL.CultistHood],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [
                "ekwd|ClothingTypeHat",
                "ekwd|ClothingTypeCultist",
            ],
            exclude: [],
        },
        {
            order: 11,
            prefix: [ICON_APPAREL.FedoraHat],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: fedoraInclude,
            exclude: [
                ...fasnachtMaskKeywordInclude,
                ...fasnachtMaskEdidInclude,
                ...gasMaskInclude,
                ...beretInclude,
                ...helmetInclude,
                ...capInclude,
                ...flowerCrownRules,
                "ekwd|cultist"
            ],
        },
        {
            order: 12,
            prefix: [ICON_APPAREL.GasMask],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: gasMaskInclude,
            exclude: [],
        },
        {
            order: 13,
            prefix: [ICON_APPAREL.Helmet],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: helmetInclude,
            exclude: [
                "edid|nohelmet",
                "edid|gasmask",
                "edid|fasnacht",
                "edid|PowerArmor",
                "ekwd|cultist"
            ],
        },
        {
            order: 14,
            prefix: [ICON_APPAREL.Asylum],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [
                "ekwd|ObjectTypeClothing",
                "ekwd|ClothingTypeAsylum",
            ],
            exclude: [],
        },
        {
            order: 15,
            prefix: [ICON_APPAREL.CarnivalCostume],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [
                "ekwd|ObjectTypeClothing",
                "ekwd|ClothingTypeHoliday",
            ],
            exclude: [
                "ekwd|hat",
                "ekwd|glasses",
            ],
        },
        {
            order: 16,
            prefix: [ICON_APPAREL.CarnivalCostume],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [
                "ekwd|ObjectTypeClothing",
                "ekwd|ClothingTypeCostume",
            ],
            exclude: [
                "ekwd|ClothingTypeDress",
                "ekwd|ClothingTypeSpacesuit",
                "ekwd|ClothingTypeCowboy"
            ],
        },
        {
            order: 17,
            prefix: [ICON_APPAREL.CowboyClothing],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [
                "ekwd|ObjectTypeClothing",
                "ekwd|ClothingTypeCowboy",
            ],
            exclude: ["ekwd|ClothingTypeHat"],
        },
        {
            order: 18,
            prefix: [ICON_APPAREL.SpacesuitClothing],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [
                "ekwd|ObjectTypeClothing",
                "ekwd|ClothingTypeSpacesuit"
            ],
            exclude: [
                "ekwd|ClothingTypeHat",
            ],
        },
        {
            order: 19,
            prefix: [ICON_APPAREL.Dress],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|ClothingTypeDress"],
            exclude: [],
        },
        {
            order: 20,
            prefix: [ICON_APPAREL.MilitaryClothing],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [
                "ekwd|ObjectTypeClothing",
                "ekwd|military"
            ],
            exclude: [],
        },
        {
            order: 21,
            prefix: [ICON_APPAREL.Suit],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|ClothingTypeFormalWear"],
            exclude: ["ekwd|ClothingTypeDress", "edid|mask"],
        },
        {
            order: 22,
            prefix: [ICON_APPAREL.Apparel],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|ObjectTypeClothing"],
            exclude: [
                "ekwd|ClothingTypeHat",
                "ekwd|ClothingTypeGasMask",
                "ekwd|ClothingTypeDress",
                "ekwd|ClothingTypeFormalWear",
            ],
        },
        {
            order: 23,
            prefix: [ICON_APPAREL.Apparel],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "edid|Armor_Disciples_Underarmor",
                "edid|MotivationalCollar",
                "edid|WeaselCollar",
                "edid|Outfit_TheMechanicOutfit_GreaseGoblin",
            ],
            exclude: [],
        }
        // "ekwd|ObjectTypeSports"
        // "ekwd|ClothingTypeCultist"
        // "ekwd|ClothingTypeHistorical"
        // "ekwd|ClothingTypeFishingHat"
        // "ekwd|ClothingTypeFormalHat"
        // "ekwd|HatTypeClown"
        // "ekwd|HatTypeTinfoil"
        // "ekwd|DiseasePrevention_Inhalation"
        // "ekwd|HatTypeHoliday"
        // "ekwd|HatTypeMilitary"
    ],
} as const satisfies RulesGroup<ICON_APPAREL>;
