import { ICON_APPAREL, ICON_UTILITY } from "@/generated/icons-enum";
import { LeftSignature, RightSignature } from "@/constants";
import type { RulesGroup } from "@/types";
import { ICON_CATEGORIES } from "@/generated/icon-categories-enum";
const objectTypeClothing = "ekwd|ObjectTypeClothing" as const;
const objectTypeArmor = "ekwd|ObjectTypeArmor" as const;
const objectTypeBasicArmor = "ekwd|ObjectTypeBasicArmor" as const;
const clothingTypeHat = "ekwd|ClothingTypeHat" as const;
const clothingTypeFishingHat = "ekwd|ClothingTypeFishingHat" as const;
const clothingTypeGlasses = "ekwd|ClothingTypeGlasses" as const;
const clothingTypeGasMask = "ekwd|ClothingTypeGasmask" as const;
const clothingTypeCostume = "ekwd|ClothingTypeCostume" as const;
const clothingTypeHoliday = "ekwd|ClothingTypeHoliday" as const;
const clothingTypeSwimsuit = "ekwd|ClothingTypeSwimsuit" as const;
const clothingTypeDress = "ekwd|ClothingTypeDress" as const;
const clothingTypeSleepwear = "ekwd|ClothingTypeSleepwear" as const;
const clothingTypeMilitary = "ekwd|ClothingTypeMilitary" as const;
const clothingTypeFormalWear = "ekwd|ClothingTypeFormalWear" as const;
const clothingTypeSpacesuit = "ekwd|ClothingTypeSpacesuit" as const;
const clothingTypeCowboy = "ekwd|ClothingTypeCowboy" as const;
const armorBodyPartHead = "ekwd|ArmorBodyPartHead" as const;
const hatTypeMilitary = "ekwd|HatTypeMilitary" as const;
const hatTypeFasnachtMask = "ekwd|HatTypeFasnachtMask" as const;
const hatTypeHalloween = "ekwd|HatTypeHalloween" as const;
const veteranMask = "edid|Veteran_Mask" as const;
// source for fasnacht: https://www.theduchessflame.com/post/fasnacht-day-parade-all-rewards
export const APPAREL_RULES_GROUP = {
    category: ICON_CATEGORIES.Apparel,
    rules: [
        {
            order: 0,
            prefix: [ICON_APPAREL.Backpack],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|ObjectTypeBackpack"],
        },
        {
            order: 1,
            prefix: [ICON_APPAREL.Underarmor],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|Armor_Vault118_UnderwearClean"],
            exclude: [],
        },
        {
            order: 2,
            prefix: [ICON_APPAREL.Underarmor],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|ObjectTypeUnderarmor",],
            exclude: [],
        },
        {
            order: 3,
            prefix: [ICON_APPAREL.Glasses],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [clothingTypeGlasses],
            exclude: [],
        },
        {
            order: 4,
            prefix: [ICON_APPAREL.FasnachtMask, ICON_UTILITY.Expensive, ICON_UTILITY.Empty, ICON_UTILITY.Empty],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                // 2019
                "edid|Headwear_Fasnacht_Mask_OldManWinter",
            ],
            exclude: [],
        },
        {
            order: 5,
            prefix: [ICON_APPAREL.FasnachtMask, ICON_UTILITY.Expensive, ICON_UTILITY.YearTwenty, ICON_UTILITY.Empty],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "edid|Armor_PowerArmor_Fasnacht_FatherWinter_Helmet",
                "edid|Headwear_Fasnacht_Mask_CrazyGuy",
                "edid|ATX_Headwear_Fasnacht_Mask_Deathclaw",
                "edid|Headwear_Fasnacht_Mask_Raven",
            ],
            exclude: [
                "edid|ATX_Headwear_Fasnacht_Mask_CrazyGuy_Blue",
                "edid|ATX_Headwear_Fasnacht_Mask_CrazyGuy_Green"
            ],
        },
        {
            order: 6,
            prefix: [ICON_APPAREL.FasnachtMask, ICON_UTILITY.Expensive, ICON_UTILITY.YearTwentyOne, ICON_UTILITY.Empty],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "edid|Headwear_Fasnacht_Mask_Brahmin",
                "edid|Headwear_Fasnacht_Mask_Jester",
                "edid|Headwear_Fasnacht_Mask_Demon",
            ],
            exclude: [],
        },
        {
            order: 7,
            prefix: [ICON_APPAREL.FasnachtMask, ICON_UTILITY.Expensive, ICON_UTILITY.YearTwentyTwo, ICON_UTILITY.Empty],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "edid|Headwear_Fasnacht_Mask_Fiend",
                "edid|Headwear_Fasnacht_Mask_Hag",
                "edid|Headwear_Fasnacht_Mask_Loon",
            ],
            exclude: [],
        },
        {
            order: 8,
            prefix: [ICON_APPAREL.FasnachtMask, ICON_UTILITY.Expensive, ICON_UTILITY.YearTwentyFour, ICON_UTILITY.Empty],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "edid|Headwear_Fasnacht_Mask_Alien_Glow",
                "edid|Headwear_Fasnacht_Mask_BlueDevil_Glow",
                "edid|Headwear_Fasnacht_Mask_HoneyBee_Glow",
                "edid|Headwear_Fasnacht_Mask_Minotaur_Glow",
                "edid|Headwear_Fasnacht_Mask_Pig_Glow",
                "edid|Headwear_Fasnacht_Mask_Robot_Glow",
                "edid|Headwear_Fasnacht_Mask_ScorchBeast_Glow",
                "edid|Headwear_Fasnacht_Mask_ScorchBeastQueen_Glow",
                "edid|Headwear_Fasnacht_Mask_Turkey_Glow",
                "edid|Headwear_Fasnacht_Mask_Unicorn_Glow",
            ],
            exclude: [],
        },
        {
            order: 9,
            prefix: [ICON_APPAREL.FasnachtMask, ICON_UTILITY.Expensive, ICON_UTILITY.YearTwentyFive, ICON_UTILITY.QOne],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "edid|Headwear_Fasnacht_Mask_Abe_Glow",
                "edid|Headwear_Fasnacht_Mask_Bigfoot_Glow",
                "edid|Headwear_Fasnacht_Mask_Jackalope_Glow",
                "edid|Headwear_Fasnacht_Mask_VeggieMan_Glow",
            ],
            exclude: [],
        },
        {
            order: 10,
            prefix: [ICON_APPAREL.FasnachtMask, ICON_UTILITY.Expensive, ICON_UTILITY.YearTwentyFive, ICON_UTILITY.QThree],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "edid|ARMO_Headwear_FasnachtMask_Owl_Glow",
                "edid|ARMO_Headwear_FasnachtMask_Jester_Glow",
                "edid|ARMO_Headwear_FasnachtCornCob_Glowing",
                "edid|ARMO_Headwear_FasnachtMask_Skull_Glow",
                "edid|ARMO_Headwear_FasnachtMask_Sun_Glow"
            ],
            exclude: [],
        },
        {
            order: 11,
            prefix: [ICON_APPAREL.FasnachtMask, ICON_UTILITY.Empty, ICON_UTILITY.Empty, ICON_UTILITY.Empty],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [hatTypeFasnachtMask],
            exclude: [],
        },
        {
            order: 12,
            prefix: [ICON_APPAREL.FasnachtMask, ICON_UTILITY.Empty, ICON_UTILITY.Empty, ICON_UTILITY.Empty],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                veteranMask,
                "edid|ClothesMistressOfMysteryVeil",
                "edid|ClothesMistressOfMysteryWornVeil"
            ],
            exclude: [],
        },
        {
            order: 13,
            prefix: [ICON_APPAREL.Mask, ICON_UTILITY.Expensive],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "edid|Headwear_EnclaveScoutUniform_Mask_Urban",
                "edid|Headwear_EnclaveScoutUniform_Mask_Forest"
            ],
            exclude: [],
        },
        {
            order: 14,
            prefix: [ICON_APPAREL.Mask, ICON_UTILITY.Empty],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [
                "ekwd|ClothingTypeMask"
            ],
            exclude: [
                hatTypeFasnachtMask,
                hatTypeMilitary,
                hatTypeHalloween,
                clothingTypeGasMask
            ],
        },
        {
            order: 15,
            prefix: [ICON_APPAREL.HalloweenHat],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [hatTypeHalloween],
            exclude: [],
        },
        {
            order: 16,
            prefix: [ICON_APPAREL.FlowerCrown],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|FlowerCrown"],
            exclude: [],
        },
        {
            order: 17,
            prefix: [ICON_APPAREL.CultistHood],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [
                clothingTypeHat,
                "ekwd|ClothingTypeCultist",
            ],
            exclude: [],
        },
        {
            order: 18,
            prefix: [ICON_APPAREL.GasMask],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [clothingTypeGasMask],
            exclude: [],
        },
        {
            order: 19,
            prefix: [ICON_APPAREL.Helmet],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [armorBodyPartHead],
            exclude: [objectTypeBasicArmor],
        },
        {
            order: 20,
            prefix: [ICON_APPAREL.SpacesuitHat],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|Headwear_Jumpsuit_SpaceSuit"],
            exclude: [],
        },
        {
            order: 21,
            prefix: [ICON_APPAREL.SpacesuitHat],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [
                clothingTypeHat,
                clothingTypeSpacesuit
            ],
            exclude: [],
        },
        {
            order: 22,
            prefix: [ICON_APPAREL.SpacesuitClothing],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [
                objectTypeClothing,
                clothingTypeSpacesuit
            ],
            exclude: [
                clothingTypeHat,
            ],
        },
        {
            order: 23,
            prefix: [ICON_APPAREL.CowboyHat],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|HatTypeCowboy"],
            exclude: [],
        },
        {
            order: 24,
            prefix: [ICON_APPAREL.CowboyHat],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|Veracio_Hat"],
            exclude: [],
        },
        {
            order: 25,
            prefix: [ICON_APPAREL.CowboyClothing],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [
                objectTypeClothing,
                clothingTypeCowboy,
            ],
            exclude: [clothingTypeHat],
        },
        {
            order: 26,
            prefix: [ICON_APPAREL.CowboyClothing],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|Outfit_NukaCowboyChaps"],
            exclude: [clothingTypeHat],
        },
        {
            order: 27,
            prefix: [ICON_APPAREL.WinterHat],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [
                clothingTypeHat,
                "ekwd|ClothingTypeWinter"
            ],
            exclude: [],
        },
        {
            order: 28,
            prefix: [ICON_APPAREL.WinterJacket],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [
                objectTypeClothing,
                "ekwd|ClothingTypeWinter"
            ],
            exclude: [
                objectTypeArmor,
                clothingTypeHat,
                clothingTypeCostume
            ],
        },
        {
            order: 29,
            prefix: [ICON_APPAREL.FishingHat],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [clothingTypeFishingHat],
            exclude: [],
        },
        {
            order: 30,
            prefix: [ICON_APPAREL.FishingOutfit],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|ClothingTypeFishingOutfit"],
            exclude: [
                clothingTypeDress,
                clothingTypeHat,
            ],
        },
        {
            order: 31,
            prefix: [ICON_APPAREL.MilitaryHat],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [hatTypeMilitary],
            exclude: [
                armorBodyPartHead,
                clothingTypeHoliday
            ],
        },
        {
            order: 32,
            prefix: [ICON_APPAREL.MilitaryClothing],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [
                objectTypeClothing,
                clothingTypeMilitary
            ],
            exclude: [],
        },
        {
            order: 33,
            prefix: [ICON_APPAREL.Asylum, ICON_UTILITY.Expensive],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|Clothes_AsylumWorkerUniformRed"],
            exclude: [],
        },
        {
            order: 34,
            prefix: [ICON_APPAREL.Asylum, ICON_UTILITY.Empty],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [
                objectTypeClothing,
                "ekwd|ClothingTypeAsylum",
            ],
            exclude: [],
        },
        {
            order: 35,
            prefix: [ICON_APPAREL.MrFuzzyHead, ICON_UTILITY.Expensive],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["form|MTR04_Clothes_AmusementPark_Camden_MascotXHead|0012879A"],
            exclude: [],
        },
        {
            order: 36,
            prefix: [ICON_APPAREL.MrFuzzyHead, ICON_UTILITY.Empty],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [
                "ekwd|HatTypeMrFuzzy",
                clothingTypeHat,
            ],
            exclude: [],
        },
        {
            order: 37,
            prefix: [ICON_APPAREL.MrFuzzyHead, ICON_UTILITY.Empty],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [
                "edid|mascot",
                "edid|head"
            ],
            exclude: [],
        },
        {
            order: 38,
            prefix: [ICON_APPAREL.MrFuzzyHead, ICON_UTILITY.Empty],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [
                "edid|mascot",
                "edid|head"
            ],
            exclude: [],
        },
        {
            order: 39,
            prefix: [ICON_APPAREL.HolidayCostume, ICON_UTILITY.Expensive],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["form|MTR04_Clothes_AmusementPark_Camden_MascotX|0009D22F"],
            exclude: [],
        },
        {
            order: 40,
            prefix: [ICON_APPAREL.HolidayCostume, ICON_UTILITY.Empty],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [
                "edid|mascot",
                "edid|clothes"
            ],
            exclude: [],
        },
        {
            order: 41,
            prefix: [ICON_APPAREL.HolidayCostume, ICON_UTILITY.Empty],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [
                objectTypeClothing,
                clothingTypeHoliday,
            ],
            exclude: [
                clothingTypeHat,
                clothingTypeDress,
                clothingTypeGlasses,
            ],
        },
        {
            order: 42,
            prefix: [ICON_APPAREL.Suit],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [clothingTypeFormalWear],
            exclude: [
                clothingTypeDress,
                clothingTypeSleepwear,
                clothingTypeMilitary,
                veteranMask
            ],
        },
        {
            order: 43,
            prefix: [ICON_APPAREL.Dress],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [clothingTypeDress],
            exclude: [],
        },
        {
            order: 44,
            prefix: [ICON_APPAREL.RaiderClothing, ICON_UTILITY.Expensive],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "edid|Clothes_Raider_Suit_01_GlovesB",
                "edid|Clothes_Raider_Suit_02A_GlovesC",
                "edid|Clothes_Raider_Suit_02B_GlovesC"
            ],
            exclude: [],
        },
        {
            order: 45,
            prefix: [ICON_APPAREL.RaiderClothing, ICON_UTILITY.Empty],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [
                objectTypeClothing,
                "ekwd|ClothingTypeRaider"
            ],
            exclude: [
                clothingTypeHat,
                objectTypeArmor,
            ],
        },
        {
            order: 46,
            prefix: [ICON_APPAREL.Sleepwear],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [
                objectTypeClothing,
                clothingTypeSleepwear
            ],
            exclude: [
                "ekwd|ObjectTypeSwimsuit",
                clothingTypeHoliday,
            ],
        },
        {
            order: 47,
            prefix: [ICON_APPAREL.Swimsuit],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [
                objectTypeClothing,
                clothingTypeSwimsuit
            ],
            exclude: [],
        },
        {
            order: 48,
            prefix: [ICON_APPAREL.HazmatSuit],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [objectTypeBasicArmor],
            exclude: [],
        },
        {
            order: 49,
            prefix: [ICON_APPAREL.HazmatSuit],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|PlayerGhoulDisguise"],
            exclude: [],
        },
        {
            order: 50,
            prefix: [ICON_APPAREL.DefaultHat, ICON_UTILITY.Expensive],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|Headwear_Responders_FiremanHat"],
            exclude: [],
        },
        {
            order: 51,
            prefix: [ICON_APPAREL.DefaultHat, ICON_UTILITY.Empty],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [clothingTypeHat],
            exclude: [hatTypeMilitary],
        },
        {
            order: 52,
            prefix: [ICON_APPAREL.DefaultClothing, ICON_UTILITY.Expensive],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "edid|Clothes_Jumpsuit_WhitePowder",
                "edid|Clothes_Jumpsuit_BOS",
                "edid|Clothes_Responders_FiremanUniform",
                "edid|Clothes_Jumpsuit_ForestCamo"
            ],
            exclude: [],
        },
        {
            order: 53,
            prefix: [ICON_APPAREL.DefaultClothing, ICON_UTILITY.Empty],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [objectTypeClothing],
            exclude: [
                clothingTypeHat,
                clothingTypeGasMask,
                clothingTypeDress,
                clothingTypeFormalWear,
                clothingTypeFishingHat,
            ],
        },
        {
            order: 54,
            prefix: [ICON_APPAREL.DefaultClothing, ICON_UTILITY.Empty],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "edid|Armor_Disciples_Underarmor",
                "edid|MotivationalCollar",
                "edid|WeaselCollar",
                "edid|Outfit_TheMechanicOutfit_GreaseGoblin",
                "edid|ClothesMistressOfMysteryEyeOfRa"
            ],
            exclude: [],
        }
    ],
} as const satisfies RulesGroup<ICON_APPAREL | ICON_UTILITY>;
