import { ICON_ARMOR } from "@/generated/icons-enum";
import { LeftSignature, POWER_ARMOR_EFFECTS, RightSignature } from "@/constants";
import type { IncludeProperty, RulesGroup } from "@/types";
import { ICON_CATEGORIES } from "@/generated/icon-categories-enum";
const vulcanRules = [
    "ekwd|PowerArmor_EnclaveVulcan"
] as const satisfies IncludeProperty[];
const excavatorRules = [
    "ekwd|PowerArmor_Excavator"
] as const satisfies IncludeProperty[];
const unionRules = [
    "ekwd|PowerArmor_Union"
] as const satisfies IncludeProperty[];
const v94Rules = [
    "ekwd|PowerArmor_V94_Ultracite"
] as const satisfies IncludeProperty[];
const hellcatRules = [
    "ekwd|PowerArmor_Hellcat"
] as const satisfies IncludeProperty[];
const ultraciteRules = [
    "ekwd|PowerArmor_Ultracite"
] as const satisfies IncludeProperty[];
const raiderRules = [
    "ekwd|PowerArmor_Raider"
] as const satisfies IncludeProperty[];
const t45Rules = [
    "ekwd|PowerArmor_t45"
] as const satisfies IncludeProperty[];
const t51Rules = [
    "ekwd|PowerArmor_t51"
] as const satisfies IncludeProperty[];
const t60Rules = [
    "ekwd|PowerArmor_t60"
] as const satisfies IncludeProperty[];
const t65Rules = [
    "ekwd|PowerArmor_T65"
] as const satisfies IncludeProperty[];
const x01Rules = [
    "ekwd|PowerArmor_x01"
] as const satisfies IncludeProperty[];
export const ARMOR_RULES_GROUP = {
    category: ICON_CATEGORIES.Armor,
    rules: [
        {
            order: 0,
            prefix: [ICON_ARMOR.PowerArmorHelmet],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|PowerArmorChassis"],
        },
        {
            order: 1,
            prefix: [ICON_ARMOR.PowerArmorHelmet],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|ArmorTypePower"],
        },
        {
            order: 2,
            prefix: [ICON_ARMOR.PowerArmorHelmet],
            leftSignature: LeftSignature.InstanceNamingRules,
            rightSignature: RightSignature.WNAM,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|PowerArmor"],
            exclude: [
                ...POWER_ARMOR_EFFECTS,
                ...vulcanRules,
                ...excavatorRules,
                ...unionRules,
                ...hellcatRules,
                ...ultraciteRules,
                ...raiderRules,
                ...v94Rules,
                ...t45Rules,
                ...t51Rules,
                ...t60Rules,
                ...t65Rules,
                ...x01Rules,
                "ekwd|PowerArmor_Helmet",
                "ekwd|PowerArmor_LeftArm",
                "ekwd|PowerArmor_RightArm",
                "ekwd|PowerArmor_LeftLeg",
                "ekwd|PowerArmor_RightLeg",
                "ekwd|PowerArmor_Torso",
            ],
        },
        {
            order: 3,
            prefix: [ICON_ARMOR.Vulcan],
            leftSignature: LeftSignature.InstanceNamingRules,
            rightSignature: RightSignature.WNAM,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: true,
            include: vulcanRules,
            exclude: [],
        },
        {
            order: 4,
            prefix: [ICON_ARMOR.Excavator],
            leftSignature: LeftSignature.InstanceNamingRules,
            rightSignature: RightSignature.WNAM,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: true,
            include: excavatorRules,
            exclude: [],
        },
        {
            order: 5,
            prefix: [ICON_ARMOR.UnionPa],
            leftSignature: LeftSignature.InstanceNamingRules,
            rightSignature: RightSignature.WNAM,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: true,
            include: unionRules,
            exclude: [],
        },
        {
            order: 6,
            prefix: [ICON_ARMOR.VNinetyFour],
            leftSignature: LeftSignature.InstanceNamingRules,
            rightSignature: RightSignature.WNAM,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: true,
            include: v94Rules,
            exclude: [],
        },
        {
            order: 7,
            prefix: [ICON_ARMOR.Hellcat],
            leftSignature: LeftSignature.InstanceNamingRules,
            rightSignature: RightSignature.WNAM,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: true,
            include: hellcatRules,
            exclude: [],
        },
        {
            order: 8,
            prefix: [ICON_ARMOR.Ultracite],
            leftSignature: LeftSignature.InstanceNamingRules,
            rightSignature: RightSignature.WNAM,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: true,
            include: ultraciteRules,
            exclude: [],
        },
        {
            order: 9,
            prefix: [ICON_ARMOR.Raider],
            leftSignature: LeftSignature.InstanceNamingRules,
            rightSignature: RightSignature.WNAM,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: true,
            include: raiderRules,
            exclude: [],
        },
        {
            order: 10,
            prefix: [ICON_ARMOR.TFortyFive],
            leftSignature: LeftSignature.InstanceNamingRules,
            rightSignature: RightSignature.WNAM,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: true,
            include: t45Rules,
            exclude: [],
        },
        {
            order: 11,
            prefix: [ICON_ARMOR.TFiftyOne],
            leftSignature: LeftSignature.InstanceNamingRules,
            rightSignature: RightSignature.WNAM,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: true,
            include: t51Rules,
            exclude: [],
        },
        {
            order: 12,
            prefix: [ICON_ARMOR.TSixty],
            leftSignature: LeftSignature.InstanceNamingRules,
            rightSignature: RightSignature.WNAM,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: true,
            include: t60Rules,
            exclude: [],
        },
        {
            order: 13,
            prefix: [ICON_ARMOR.TSixtyFive],
            leftSignature: LeftSignature.InstanceNamingRules,
            rightSignature: RightSignature.WNAM,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: true,
            include: t65Rules,
            exclude: [],
        },
        {
            order: 14,
            prefix: [ICON_ARMOR.XOne],
            leftSignature: LeftSignature.InstanceNamingRules,
            rightSignature: RightSignature.WNAM,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: true,
            include: x01Rules,
            exclude: [],
        },
        {
            order: 15,
            prefix: [ICON_ARMOR.Underarmor],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|Armor_Vault118_UnderwearClean"],
            exclude: [],
        },
        {
            order: 16,
            prefix: [ICON_ARMOR.Underarmor],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|ObjectTypeUnderarmor",],
            exclude: [],
        },
        {
            order: 17,
            prefix: [ICON_ARMOR.Spacesuit],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "edid|SpaceSuit",
                "edid|HazmatSuit"
            ],
            exclude: [],
        },
        {
            order: 18,
            prefix: [ICON_ARMOR.ChestArmor],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|ObjectTypeArmor"],
            exclude: [
                "ekwd|ClothingTypeSpacesuit",
                "ekwd|ArmorBodyPartHands",
                "ekwd|ArmorBodyPartFeet",
            ],
        },
        {
            order: 19,
            prefix: [ICON_ARMOR.ChestArmor],
            leftSignature: LeftSignature.InstanceNamingRules,
            rightSignature: RightSignature.WNAM,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|PowerArmor_Torso"],
            exclude: [],
        },
        {
            order: 20,
            prefix: [ICON_ARMOR.ArmorRightArm],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [
                "ekwd|ObjectTypeArmor",
                "ekwd|ArmorBodyPartHands",
                "edid|right",
            ],
            exclude: ["ekwd|ArmorTypePower"],
        },
        {
            order: 21,
            prefix: [ICON_ARMOR.ArmorRightArm],
            leftSignature: LeftSignature.InstanceNamingRules,
            rightSignature: RightSignature.WNAM,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|PowerArmor_RightArm"],
            exclude: [],
        },
        {
            order: 22,
            prefix: [ICON_ARMOR.ArmorLeftArm],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [
                "ekwd|ObjectTypeArmor",
                "ekwd|ArmorBodyPartHands",
                "edid|left",
            ],
            exclude: ["ekwd|ArmorTypePower"],
        },
        {
            order: 23,
            prefix: [ICON_ARMOR.ArmorLeftArm],
            leftSignature: LeftSignature.InstanceNamingRules,
            rightSignature: RightSignature.WNAM,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|PowerArmor_LeftArm"],
            exclude: [],
        },
        {
            order: 24,
            prefix: [ICON_ARMOR.ArmorRightLeg],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [
                "ekwd|ObjectTypeArmor",
                "ekwd|ArmorBodyPartFeet",
                "edid|right",
            ],
            exclude: ["ekwd|ArmorTypePower"],
        },
        {
            order: 25,
            prefix: [ICON_ARMOR.ArmorRightLeg],
            leftSignature: LeftSignature.InstanceNamingRules,
            rightSignature: RightSignature.WNAM,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|PowerArmor_RightLeg"],
            exclude: [],
        },
        {
            order: 26,
            prefix: [ICON_ARMOR.ArmorLeftLeg],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [
                "ekwd|ObjectTypeArmor",
                "ekwd|ArmorBodyPartFeet",
                "edid|left",
            ],
            exclude: ["ekwd|ArmorTypePower"],
        },
        {
            order: 27,
            prefix: [ICON_ARMOR.ArmorLeftLeg],
            leftSignature: LeftSignature.InstanceNamingRules,
            rightSignature: RightSignature.WNAM,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|PowerArmor_LeftLeg"],
            exclude: [],
        }
    ],
} as const satisfies RulesGroup<ICON_ARMOR>;
