import { ICON_ARMOR } from "@/generated/icons-enum";
import { LeftSignature, RightSignature } from "@/constants";
import type { RulesGroup } from "@/types";
import { ICON_CATEGORIES } from "@/generated/icon-categories-enum";
export const ARMOR_RULES_GROUP = {
    category: ICON_CATEGORIES.Armor,
    rules: [
        {
            order: 0,
            prefix: [ICON_ARMOR.TFortyFive],
            leftSignature: LeftSignature.InstanceNamingRules,
            rightSignature: RightSignature.WNAM,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: true,
            include: ["ekwd|t45"],
            exclude: [],
        },
        {
            order: 1,
            prefix: [ICON_ARMOR.TFivtyOne],
            leftSignature: LeftSignature.InstanceNamingRules,
            rightSignature: RightSignature.WNAM,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: true,
            include: ["ekwd|t51"],
            exclude: [],
        },
        {
            order: 2,
            prefix: [ICON_ARMOR.TSixty],
            leftSignature: LeftSignature.InstanceNamingRules,
            rightSignature: RightSignature.WNAM,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: true,
            include: ["ekwd|t60"],
            exclude: [],
        },
        {
            order: 3,
            prefix: [ICON_ARMOR.TSixtyFive],
            leftSignature: LeftSignature.InstanceNamingRules,
            rightSignature: RightSignature.WNAM,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: true,
            include: ["ekwd|PowerArmor_T65"],
            exclude: [],
        },
        {
            order: 4,
            prefix: [ICON_ARMOR.XOne],
            leftSignature: LeftSignature.InstanceNamingRules,
            rightSignature: RightSignature.WNAM,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: true,
            include: ["ekwd|x01"],
            exclude: [],
        },
        {
            order: 5,
            prefix: [ICON_ARMOR.PowerArmorHelmet],
            leftSignature: LeftSignature.InstanceNamingRules,
            rightSignature: RightSignature.WNAM,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|PowerArmor"],
            exclude: [
                "ekwd|PowerArmor_Helmet",
                "ekwd|PowerArmor_LeftArm",
                "ekwd|PowerArmor_RightArm",
                "ekwd|PowerArmor_LeftLeg",
                "ekwd|PowerArmor_RightLeg",
                "ekwd|PowerArmor_Torso",
                "ekwd|t45",
                "ekwd|t51",
                "ekwd|t60",
                "ekwd|PowerArmor_T65",
                "ekwd|x01",
            ],
        },
        {
            order: 6,
            prefix: [ICON_ARMOR.Underarmor],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|ObjectTypeUnderarmor"],
            exclude: [],
        },
        {
            order: 7,
            prefix: [ICON_ARMOR.Spacesuit],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|ClothingTypeSpacesuit"],
            exclude: [],
        },
        {
            order: 8,
            prefix: [ICON_ARMOR.ChestArmor],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|ObjectTypeArmor"],
            exclude: [
                "ekwd|ClothingTypeSpacesuit",
                "ekwd|ArmorBodyPartHands",
                "ekwd|ArmorBodyPartFeet",
            ],
        },
        {
            order: 9,
            prefix: [ICON_ARMOR.ArmorRightArm],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [
                "ekwd|ObjectTypeArmor",
                "ekwd|ArmorBodyPartHands",
                "edid|right",
            ],
            exclude: ["ekwd|ArmorTypePower"],
        },
        {
            order: 10,
            prefix: [ICON_ARMOR.ArmorLeftArm],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [
                "ekwd|ObjectTypeArmor",
                "ekwd|ArmorBodyPartHands",
                "edid|left",
            ],
            exclude: ["ekwd|ArmorTypePower"],
        },
        {
            order: 11,
            prefix: [ICON_ARMOR.ArmorRightLeg],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [
                "ekwd|ObjectTypeArmor",
                "ekwd|ArmorBodyPartFeet",
                "edid|right",
            ],
            exclude: ["ekwd|ArmorTypePower"],
        },
        {
            order: 12,
            prefix: [ICON_ARMOR.ArmorLeftLeg],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [
                "ekwd|ObjectTypeArmor",
                "ekwd|ArmorBodyPartFeet",
                "edid|left",
            ],
            exclude: ["ekwd|ArmorTypePower"],
        }
    ],
} as const satisfies RulesGroup<ICON_ARMOR>;
