import { ICON_ARMOR } from "@/generated/icons-enum";
import { LeftSignature, RightSignature } from "@/constants";
import type { IncludeProperty, RulesGroup } from "@/types";
import { ICON_CATEGORIES } from "@/generated/icon-categories-enum";
const excavatorInclude: IncludeProperty[] = [
    "ekwd|excavator"
];
const t45include: IncludeProperty[] = [
    "ekwd|t45"
];
const t51include: IncludeProperty[] = [
    "ekwd|t51"
];
const t60include: IncludeProperty[] = [
    "ekwd|t60"
];
const t65include: IncludeProperty[] = [
    "ekwd|PowerArmor_T65"
];
const x01include: IncludeProperty[] = [
    "ekwd|x01"
];
export const ARMOR_RULES_GROUP = {
    category: ICON_CATEGORIES.Armor,
    rules: [
        {
            order: 0,
            prefix: [ICON_ARMOR.PowerArmorHelmet],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|PowerArmorChassis"],
        },
        {
            order: 1,
            prefix: [ICON_ARMOR.PowerArmorHelmet],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|ArmorTypePower"],
        },
        {
            order: 2,
            prefix: [ICON_ARMOR.PowerArmorHelmet],
            leftSignature: LeftSignature.InstanceNamingRules,
            rightSignature: RightSignature.WNAM,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|PowerArmor"],
            exclude: [
                "ekwd|PowerArmor_Helmet",
                "ekwd|PowerArmor_LeftArm",
                "ekwd|PowerArmor_RightArm",
                "ekwd|PowerArmor_LeftLeg",
                "ekwd|PowerArmor_RightLeg",
                "ekwd|PowerArmor_Torso",
                ...t45include,
                ...t51include,
                ...t60include,
                ...t65include,
                ...x01include,
            ],
        },
        {
            order: 3,
            prefix: [ICON_ARMOR.Excavator],
            leftSignature: LeftSignature.InstanceNamingRules,
            rightSignature: RightSignature.WNAM,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: excavatorInclude,
            exclude: [],
        },
        {
            order: 4,
            prefix: [ICON_ARMOR.TFortyFive],
            leftSignature: LeftSignature.InstanceNamingRules,
            rightSignature: RightSignature.WNAM,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: true,
            include: t45include,
            exclude: [],
        },
        {
            order: 5,
            prefix: [ICON_ARMOR.TFivtyOne],
            leftSignature: LeftSignature.InstanceNamingRules,
            rightSignature: RightSignature.WNAM,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: true,
            include: t51include,
            exclude: [],
        },
        {
            order: 6,
            prefix: [ICON_ARMOR.TSixty],
            leftSignature: LeftSignature.InstanceNamingRules,
            rightSignature: RightSignature.WNAM,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: true,
            include: t60include,
            exclude: [],
        },
        {
            order: 7,
            prefix: [ICON_ARMOR.TSixtyFive],
            leftSignature: LeftSignature.InstanceNamingRules,
            rightSignature: RightSignature.WNAM,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: true,
            include: t65include,
            exclude: [],
        },
        {
            order: 8,
            prefix: [ICON_ARMOR.XOne],
            leftSignature: LeftSignature.InstanceNamingRules,
            rightSignature: RightSignature.WNAM,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: true,
            include: x01include,
            exclude: [],
        },
        {
            order: 9,
            prefix: [ICON_ARMOR.Underarmor],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|Armor_Vault118_UnderwearClean"],
            exclude: [],
        },
        {
            order: 10,
            prefix: [ICON_ARMOR.Underarmor],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|ObjectTypeUnderarmor",],
            exclude: [],
        },
        {
            order: 11,
            prefix: [ICON_ARMOR.Spacesuit],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "edid|SpaceSuit",
                "edid|HazmatSuit"
            ],
            exclude: [],
        },
        {
            order: 12,
            prefix: [ICON_ARMOR.ChestArmor],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|ObjectTypeArmor"],
            exclude: [
                "ekwd|ClothingTypeSpacesuit",
                "ekwd|ArmorBodyPartHands",
                "ekwd|ArmorBodyPartFeet",
            ],
        },
        {
            order: 13,
            prefix: [ICON_ARMOR.ArmorRightArm],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [
                "ekwd|ObjectTypeArmor",
                "ekwd|ArmorBodyPartHands",
                "edid|right",
            ],
            exclude: ["ekwd|ArmorTypePower"],
        },
        {
            order: 14,
            prefix: [ICON_ARMOR.ArmorLeftArm],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [
                "ekwd|ObjectTypeArmor",
                "ekwd|ArmorBodyPartHands",
                "edid|left",
            ],
            exclude: ["ekwd|ArmorTypePower"],
        },
        {
            order: 15,
            prefix: [ICON_ARMOR.ArmorRightLeg],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [
                "ekwd|ObjectTypeArmor",
                "ekwd|ArmorBodyPartFeet",
                "edid|right",
            ],
            exclude: ["ekwd|ArmorTypePower"],
        },
        {
            order: 16,
            prefix: [ICON_ARMOR.ArmorLeftLeg],
            leftSignature: LeftSignature.Armor,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [
                "ekwd|ObjectTypeArmor",
                "ekwd|ArmorBodyPartFeet",
                "edid|left",
            ],
            exclude: ["ekwd|ArmorTypePower"],
        }
    ],
} as const satisfies RulesGroup<ICON_ARMOR>;
