import { ICON_FOOD } from "@/generated/icons-enum";
import { LeftSignature, RightSignature } from "@/constants";
import type { IncludeProperty, RulesGroup } from "@/types";
import { ICON_CATEGORIES } from "@/generated/icon-categories-enum";
const objectTypeBubblegum = "ekwd|ObjectTypeBubblegum" as const;
const milkRules = [
    "edid|milk",
    "edid|cream"
] as const satisfies IncludeProperty[];
const petsFoodRules = [
    "edid|PETS_"
] as const satisfies IncludeProperty[];
const meatRule = "ekwd|IngredientTypeMeat" as const;
export const FOOD_RULES_GROUP = {
    category: ICON_CATEGORIES.Food,
    rules: [
        {
            order: 0,
            prefix: [ICON_FOOD.Toxic],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "edid|moldy",
                "edid|diseased",
                "edid|spoiled",
                "edid|HighRadiationFluids",
                "edid|GulperVenom"
            ],
            exclude: [...milkRules],
        },
        {
            order: 1,
            prefix: [ICON_FOOD.BottleOfWater],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|DrinkTypeWater"],
            exclude: [
                ...milkRules,
                "edid|WaterDirty"
            ],
        },
        {
            order: 2,
            prefix: [ICON_FOOD.DirtyWater],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|WaterDirty"],
            exclude: [],
        },
        {
            order: 3,
            prefix: [ICON_FOOD.NukaCola],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|ObjectTypeDrink", "ekwd|DrinkTypeSoda"],
            exclude: [],
        },
        {
            order: 4,
            prefix: [ICON_FOOD.WeightIncreaser],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|CarryWeight"],
            exclude: [],
        },
        {
            order: 5,
            prefix: [ICON_FOOD.Beer],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "edid|beer",
                "edid|BallisticBock",
                "edid|HoppyHunter",
                "edid|NewRiverRedAle",
                "edid|OakHollerLager",
                "edid|BlackwaterBrew",
                "edid|HighVoltageHefe",
                "edid|RadAntLager",
                "edid|OldPossum",
                "edid|PickaxePilsner",
            ],
            exclude: [],
        },
        {
            order: 6,
            prefix: [ICON_FOOD.Wine],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|WineAlcoholType"],
            exclude: [],
        },
        {
            order: 7,
            prefix: [ICON_FOOD.Whiskey],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|DrinkTypeLiquor"],
            exclude: [],
        },
        {
            order: 8,
            prefix: [ICON_FOOD.FermentedAlcohol],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|FermenterItem"],
            exclude: [],
        },
        {
            order: 9,
            prefix: [ICON_FOOD.Juice],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|DrinkTypeJuice"],
            exclude: [],
        },
        {
            order: 10,
            prefix: [ICON_FOOD.Juice],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "edid|SunshineOil",
                "edid|ToxicSootFlowerHerbCookedPaste"
            ],
            exclude: [],
        },
        {
            order: 11,
            prefix: [ICON_FOOD.Tea],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|DrinkTypeTea"],
            exclude: ["ekwd|IngredientTypeBlood"],
        },
        {
            order: 12,
            prefix: [ICON_FOOD.Milk],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [...milkRules],
            exclude: [],
        },
        {
            order: 13,
            prefix: [ICON_FOOD.Salad],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [
                "ekwd|ObjectTypeFood",
                "ekwd|MealTypeCooked",
                "ekwd|IngredientTypeFruit",
            ],
            exclude: [meatRule],
        },
        {
            order: 14,
            prefix: [ICON_FOOD.Salad],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "edid|CornPoneCooked",
                "edid|AnglerLureWeedVegetableCooked",
                "edid|BrainBombsGourmet",
                "edid|ChallysFeed",
                "edid|SwampPlantCookedTofu",
                "edid|SapVegetableCooked"
            ],
            exclude: [meatRule],
        },
        {
            order: 15,
            prefix: [ICON_FOOD.Soup],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [
                "ekwd|ObjectTypeFood",
                "ekwd|IngredientTypeVegetable",
                "ekwd|MealTypeSoup",
            ],
            exclude: [meatRule],
        },
        {
            order: 16,
            prefix: [ICON_FOOD.Cake],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|ObjectTypeCakesPies"],
            exclude: [meatRule],
        },
        {
            order: 17,
            prefix: [ICON_FOOD.Candy],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|ObjectTypeCandy"],
            exclude: [objectTypeBubblegum],
        },
        {
            order: 18,
            prefix: [ICON_FOOD.CannedFood],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|ObjectTypeFood", "ekwd|MealTypePackaged"],
            exclude: ["ekwd|ObjectTypeCandy", "ekwd|ObjectTypeCakesPies"],
        },
        {
            order: 19,
            prefix: [ICON_FOOD.Bubblegum],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [objectTypeBubblegum],
            exclude: [],
        },
        {
            order: 20,
            prefix: [ICON_FOOD.Cake],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "edid|PumpkinPieTasty",
                "edid|PotholePotpie",
                "edid|CarnivalPie",
                "edid|MysteryMeatPieTasty",
                "edid|StarlightBerryCookedCobbler",
                "edid|MirelurkAndBloodleafGourmet",
                "edid|CranberryCookedCobbler",
                "edid|SheepsquatchMeatTasty",
                "edid|SweetRollGourmet",
                "edid|MudCookie"
            ],
            exclude: [],
        },
        {
            order: 21,
            prefix: [ICON_FOOD.MeatSoup],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "edid|GulperMeatCooked",
                "edid|RadStagMeatTastyStew",
                "edid|ScorchBeastTastyStew",
                "edid|StingwingMeatTastyStew",
                "edid|VenisonAndTatoStew_Psycho",
                "edid|VenisonAndTatoStew_Spiced",
                "edid|ChickenMeatCookedSoup",
                "edid|IguanaMeatTastySoup"
            ],
            exclude: [],
        },
        {
            order: 22,
            prefix: [ICON_FOOD.CookedMeat],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [
                "ekwd|ObjectTypeFood",
                meatRule,
                "ekwd|MealTypeCooked",
            ],
            exclude: [
                ...petsFoodRules,
                "ekwd|MealTypeSoup"
            ],
        },
        {
            order: 23,
            prefix: [ICON_FOOD.RawMeat],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|ObjectTypeFood", meatRule],
            exclude: [
                "ekwd|MealTypeCooked",
                "edid|MirelurkEgg",
                "edid|DeathclawEgg",
                "edid|MothmanEgg",
                "edid|RadToadEgg",
                "edid|RadscorpionEgg",
            ],
        },
        {
            order: 24,
            prefix: [ICON_FOOD.PetFood],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [...petsFoodRules],
            exclude: [],
        },
        {
            order: 25,
            prefix: [ICON_FOOD.Eggs],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "edid|MirelurkEgg",
                "edid|DeathclawEgg",
                "edid|MothmanEgg",
                "edid|RadToadEgg",
                "edid|RadscorpionEgg",
            ],
            exclude: [],
        },
        {
            order: 26,
            prefix: [ICON_FOOD.TickBlood],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|TickBlood"],
            exclude: [],
        },
        {
            order: 27,
            prefix: [ICON_FOOD.Berries],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: ["ekwd|PlantTypeBerry"],
            exclude: [],
        },
        {
            order: 28,
            prefix: [ICON_FOOD.Vegetable],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "ekwd|PlantTypeVegetable",
                "ekwd|PlantTypeGourd",
                "ekwd|PlantTypeMelon",
            ],
            exclude: ["ekwd|PlantTypeFlowers"],
        },
        {
            order: 29,
            prefix: [ICON_FOOD.Vegetable],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|MutfruitFruit"],
            exclude: [],
        },
        {
            order: 30,
            prefix: [ICON_FOOD.Flowers],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "ekwd|ObjectTypeFlowers",
                "ekwd|PlantTypeAster",
                "ekwd|PlantTypeStranglerHerb",
            ],
            exclude: [],
        },
        {
            order: 31,
            prefix: [ICON_FOOD.Mushrooms],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "edid|BlightVegetable",
                "edid|BrainFungusVegetable",
                "edid|GutShroomVegetable",
                "edid|CaveFungusVegetable",
                "edid|GlowingFungusVegetable",
                "edid|MegaSlothMushroomVegetable",
                "edid|FirecapVegetable",
            ],
            exclude: ["ekwd|MealTypeCooked"],
        },
        {
            order: 32,
            prefix: [ICON_FOOD.Honey],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|honey"],
            exclude: ["ekwd|DrinkTypeAlcohol", "ekwd|ObjectTypeCandy"],
        },
        {
            order: 33,
            prefix: [ICON_FOOD.Flavor],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|IngredientTypeFlavor"],
            exclude: [],
        }
    ],
} as const satisfies RulesGroup<ICON_FOOD>;
