import { ICON_FOOD } from "@/generated/icons-enum";
import { LeftSignature, RightSignature } from "@/constants";
import type { IncludeProperty, RulesGroup } from "@/types";
import { ICON_CATEGORIES } from "@/generated/icon-categories-enum";
const milkRules = [
    "edid|milk",
    "edid|cream"
] as const satisfies IncludeProperty[];
const petsFoodRules = [
    "edid|PETS_"
] as const satisfies IncludeProperty[];
const objectTypeFood = "ekwd|ObjectTypeFood" as const;
const objectTypeBubblegum = "ekwd|ObjectTypeBubblegum" as const;
const objectTypeFish = "ekwd|ObjectTypeFish" as const;
const mealTypeCooked = "ekwd|MealTypeCooked" as const;
const mealTypeSoup = "ekwd|MealTypeSoup" as const;
const ingredientTypeMeat = "ekwd|IngredientTypeMeat" as const;
const ingredientTypeVegetable = "ekwd|IngredientTypeVegetable" as const;
const fishTypeSawgill = "ekwd|Fishing_FishType_Sawgill" as const;
const fishTypeGeneric = "ekwd|Fishing_FishType_generic" as const;
const cannery = "edid|_cannery" as const;
export const FOOD_RULES_GROUP = {
    category: ICON_CATEGORIES.Food,
    rules: [
        {
            order: 0,
            prefix: [ICON_FOOD.BottleOfWater],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|DrinkTypeWater"],
            exclude: [
                ...milkRules,
                "edid|WaterDirty"
            ],
        },
        {
            order: 1,
            prefix: [ICON_FOOD.DirtyWater],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|WaterDirty"],
            exclude: [],
        },
        {
            order: 2,
            prefix: [ICON_FOOD.NukaCola],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|ObjectTypeDrink", "ekwd|DrinkTypeSoda"],
            exclude: [],
        },
        {
            order: 3,
            prefix: [ICON_FOOD.WeightIncreaser],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|CarryWeight"],
            exclude: [],
        },
        {
            order: 4,
            prefix: [ICON_FOOD.Beer],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "edid|beer",
                "edid|BallisticBock",
                "edid|HoppyHunter",
                "edid|NewRiverRedAle",
                "edid|OakHollerLager",
                "edid|BlackwaterBrew",
                "edid|HighVoltageHefe",
                "edid|RadAntLager",
                "edid|OldPossum",
                "edid|PickaxePilsner",
            ],
            exclude: [],
        },
        {
            order: 5,
            prefix: [ICON_FOOD.Wine],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|WineAlcoholType"],
            exclude: [],
        },
        {
            order: 6,
            prefix: [ICON_FOOD.Whiskey],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|DrinkTypeLiquor"],
            exclude: [],
        },
        {
            order: 7,
            prefix: [ICON_FOOD.FermentedAlcohol],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|FermenterItem"],
            exclude: [],
        },
        {
            order: 8,
            prefix: [ICON_FOOD.Juice],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|DrinkTypeJuice"],
            exclude: [],
        },
        {
            order: 9,
            prefix: [ICON_FOOD.Juice],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "edid|SunshineOil",
                "edid|ToxicSootFlowerHerbCookedPaste"
            ],
            exclude: [],
        },
        {
            order: 10,
            prefix: [ICON_FOOD.Tea],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|DrinkTypeTea"],
            exclude: ["ekwd|IngredientTypeBlood"],
        },
        {
            order: 11,
            prefix: [ICON_FOOD.Milk],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [...milkRules],
            exclude: [objectTypeFish],
        },
        {
            order: 12,
            prefix: [ICON_FOOD.SaladCanned],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [
                ingredientTypeVegetable,
                cannery
            ],
            exclude: [ingredientTypeMeat],
        },
        {
            order: 13,
            prefix: [ICON_FOOD.Salad],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [
                objectTypeFood,
                mealTypeCooked,
                "ekwd|IngredientTypeFruit",
            ],
            exclude: [ingredientTypeMeat],
        },
        {
            order: 14,
            prefix: [ICON_FOOD.Salad],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "edid|CornPoneCooked",
                "edid|AnglerLureWeedVegetableCooked",
                "edid|BrainBombsGourmet",
                "edid|ChallysFeed",
                "edid|SwampPlantCookedTofu",
                "edid|SapVegetableCooked"
            ],
            exclude: [ingredientTypeMeat],
        },
        {
            order: 15,
            prefix: [ICON_FOOD.Soup],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [
                objectTypeFood,
                ingredientTypeVegetable,
                mealTypeSoup,
            ],
            exclude: [ingredientTypeMeat],
        },
        {
            order: 16,
            prefix: [ICON_FOOD.Cake],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|ObjectTypeCakesPies"],
            exclude: [ingredientTypeMeat],
        },
        {
            order: 17,
            prefix: [ICON_FOOD.Candy],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|ObjectTypeCandy"],
            exclude: [objectTypeBubblegum],
        },
        {
            order: 18,
            prefix: [ICON_FOOD.CannedFood],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [
                objectTypeFood,
                "ekwd|MealTypePackaged"
            ],
            exclude: [
                "ekwd|ObjectTypeCandy",
                "ekwd|ObjectTypeCakesPies"
            ],
        },
        {
            order: 19,
            prefix: [ICON_FOOD.Bubblegum],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [objectTypeBubblegum],
            exclude: [],
        },
        {
            order: 20,
            prefix: [ICON_FOOD.Cake],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: ["ekwd|ObjectTypeCakesPies"],
            exclude: [ingredientTypeMeat],
        },
        {
            order: 21,
            prefix: [ICON_FOOD.Cake],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "edid|MudCookie",
                "edid|SweetRollGourmet"
            ],
            exclude: [ingredientTypeMeat],
        },
        {
            order: 22,
            prefix: [ICON_FOOD.MeatCanned],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [
                ingredientTypeMeat,
                cannery
            ],
            exclude: [],
        },
        {
            order: 23,
            prefix: [ICON_FOOD.MeatSoup],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "edid|GulperMeatCooked",
                "edid|RadStagMeatTastyStew",
                "edid|ScorchBeastTastyStew",
                "edid|StingwingMeatTastyStew",
                "edid|VenisonAndTatoStew_Psycho",
                "edid|VenisonAndTatoStew_Spiced",
                "edid|ChickenMeatCookedSoup",
                "edid|IguanaMeatTastySoup",
                "edid|VenisonAndTatoStew_Stimpak",
            ],
            exclude: [],
        },
        {
            order: 24,
            prefix: [ICON_FOOD.MeatCooked],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [
                objectTypeFood,
                ingredientTypeMeat,
                mealTypeCooked,
            ],
            exclude: [
                ...petsFoodRules,
                mealTypeSoup
            ],
        },
        {
            order: 25,
            prefix: [ICON_FOOD.MeatRaw],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [
                objectTypeFood,
                ingredientTypeMeat
            ],
            exclude: [
                mealTypeCooked,
                objectTypeFish,
                "edid|MirelurkEgg",
                "edid|DeathclawEgg",
                "edid|MothmanEgg",
                "edid|RadToadEgg",
                "edid|RadscorpionEgg",
            ],
        },
        {
            order: 26,
            prefix: [ICON_FOOD.FishLegend],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|Fishing_FishType_LocalLegend"],
            exclude: [],
        },
        {
            order: 27,
            prefix: [ICON_FOOD.FishAxolotl],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|Fishing_FishType_Axolotl"],
            exclude: [],
        },
        {
            order: 28,
            prefix: [ICON_FOOD.FishGlowing],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|Fishing_FishType_Glowing"],
            exclude: [],
        },
        {
            order: 29,
            prefix: [ICON_FOOD.FishUncommon],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [objectTypeFish],
            exclude: [
                fishTypeSawgill,
                fishTypeGeneric,
            ],
        },
        {
            order: 30,
            prefix: [ICON_FOOD.FishCommon],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [fishTypeSawgill],
            exclude: [],
        },
        {
            order: 31,
            prefix: [ICON_FOOD.FishGeneric],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [fishTypeGeneric],
            exclude: [],
        },
        {
            order: 32,
            prefix: [ICON_FOOD.PetFood],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [...petsFoodRules],
            exclude: [],
        },
        {
            order: 33,
            prefix: [ICON_FOOD.Eggs],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "edid|MirelurkEgg",
                "edid|DeathclawEgg",
                "edid|MothmanEgg",
                "edid|RadToadEgg",
                "edid|RadscorpionEgg",
            ],
            exclude: [],
        },
        {
            order: 34,
            prefix: [ICON_FOOD.Liquid],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "edid|TickBlood",
                "edid|BioluminescentFluidPotion"
            ],
            exclude: ["edid|BioluminescentFluidPotion_Spoiled"],
        },
        {
            order: 35,
            prefix: [ICON_FOOD.Berries],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: ["ekwd|PlantTypeBerry"],
            exclude: [],
        },
        {
            order: 36,
            prefix: [ICON_FOOD.Vegetable],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "ekwd|PlantTypeVegetable",
                "ekwd|PlantTypeGourd",
                "ekwd|PlantTypeMelon",
                "ekwd|PlantTypeSap",
            ],
            exclude: ["ekwd|PlantTypeFlowers"],
        },
        {
            order: 37,
            prefix: [ICON_FOOD.Vegetable],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "edid|CorpseFlowerSeedsFruit",
                "edid|CorpseFlowerStamenFruit"
            ],
            exclude: [],
        },
        {
            order: 38,
            prefix: [ICON_FOOD.Vegetable],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|MutfruitFruit"],
            exclude: [],
        },
        {
            order: 39,
            prefix: [ICON_FOOD.Flowers],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "ekwd|ObjectTypeFlowers",
                "ekwd|PlantTypeAster",
                "ekwd|PlantTypeStranglerHerb",
            ],
            exclude: [],
        },
        {
            order: 40,
            prefix: [ICON_FOOD.Mushrooms],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "edid|BlightVegetable",
                "edid|BrainFungusVegetable",
                "edid|GutShroomVegetable",
                "edid|CaveFungusVegetable",
                "edid|GlowingFungusVegetable",
                "edid|MegaSlothMushroomVegetable",
                "edid|FirecapVegetable",
            ],
            exclude: [mealTypeCooked],
        },
        {
            order: 41,
            prefix: [ICON_FOOD.Honey],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|honey"],
            exclude: ["ekwd|DrinkTypeAlcohol", "ekwd|ObjectTypeCandy"],
        },
        {
            order: 42,
            prefix: [ICON_FOOD.Flavor],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|IngredientTypeFlavor"],
            exclude: [],
        },
        {
            order: 43,
            prefix: [ICON_FOOD.Toxic],
            leftSignature: LeftSignature.Alchemy,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "edid|moldy",
                "edid|diseased",
                "edid|spoiled",
                "edid|HighRadiationFluids",
                "edid|GulperVenom"
            ],
            exclude: [...milkRules],
        }
    ],
} as const satisfies RulesGroup<ICON_FOOD>;
