import { ICON_FOOD } from '@/generated/icons-enum';
import { LeftSignature, RightSignature } from '@/constants';
import type { RulesGroup } from '@/types';
import { ICON_CATEGORIES } from '@/generated/icon-categories-enum';

export const FOOD_RULES_GROUP = {
  category: ICON_CATEGORIES.Food,
  rules: [
    {
      order: 0,
      prefix: [ICON_FOOD.Toxic],
      leftSignature: LeftSignature.Alchemy,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: true,
      isFullReplaced: false,
      header: '0x22d3',
      include: ['edid|moldy', 'edid|diseased', 'edid|spoiled'],
      exclude: ['edid|milk'],
    },
    {
      order: 1,
      prefix: [ICON_FOOD.BottleOfWater],
      leftSignature: LeftSignature.Alchemy,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x22d4',
      include: ['ekwd|DrinkTypeWater'],
      exclude: ['edid|WaterDirty', 'edid|milk'],
    },
    {
      order: 2,
      prefix: [ICON_FOOD.DirtyWater],
      leftSignature: LeftSignature.Alchemy,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x22d5',
      include: ['edid|WaterDirty'],
      exclude: [],
    },
    {
      order: 3,
      prefix: [ICON_FOOD.NukaCola],
      leftSignature: LeftSignature.Alchemy,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x22d6',
      include: ['ekwd|ObjectTypeDrink', 'ekwd|DrinkTypeSoda'],
      exclude: [],
    },
    {
      order: 4,
      prefix: [ICON_FOOD.WeightIncreaser],
      leftSignature: LeftSignature.Alchemy,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x22d7',
      include: ['edid|CarryWeight'],
      exclude: [],
    },
    {
      order: 5,
      prefix: [ICON_FOOD.Beer],
      leftSignature: LeftSignature.Alchemy,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: true,
      isFullReplaced: false,
      header: '0x22d8',
      include: [
        'edid|beer',
        'edid|BallisticBock',
        'edid|HoppyHunter',
        'edid|NewRiverRedAle',
        'edid|OakHollerLager',
        'edid|BlackwaterBrew',
        'edid|HighVoltageHefe',
        'edid|RadAntLager',
        'edid|OldPossum',
        'edid|PickaxePilsner',
      ],
      exclude: [],
    },
    {
      order: 6,
      prefix: [ICON_FOOD.Wine],
      leftSignature: LeftSignature.Alchemy,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x22d9',
      include: ['ekwd|WineAlcoholType'],
      exclude: [],
    },
    {
      order: 7,
      prefix: [ICON_FOOD.Whiskey],
      leftSignature: LeftSignature.Alchemy,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x22da',
      include: ['ekwd|DrinkTypeLiquor'],
      exclude: [],
    },
    {
      order: 8,
      prefix: [ICON_FOOD.FermentedAlcohol],
      leftSignature: LeftSignature.Alchemy,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x22db',
      include: ['ekwd|FermenterItem'],
      exclude: [],
    },
    {
      order: 9,
      prefix: [ICON_FOOD.Juice],
      leftSignature: LeftSignature.Alchemy,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x22dc',
      include: ['ekwd|DrinkTypeJuice'],
      exclude: [],
    },
    {
      order: 10,
      prefix: [ICON_FOOD.Tea],
      leftSignature: LeftSignature.Alchemy,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x22dd',
      include: ['ekwd|DrinkTypeTea'],
      exclude: ['ekwd|IngredientTypeBlood'],
    },
    {
      order: 11,
      prefix: [ICON_FOOD.Milk],
      leftSignature: LeftSignature.Alchemy,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x22de',
      include: ['edid|milk'],
      exclude: [],
    },
    {
      order: 12,
      prefix: [ICON_FOOD.Salad],
      leftSignature: LeftSignature.Alchemy,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x22df',
      include: [
        'ekwd|ObjectTypeFood',
        'ekwd|MealTypeCooked',
        'ekwd|IngredientTypeFruit',
      ],
      exclude: ['ekwd|IngredientTypeMeat'],
    },
    {
      order: 13,
      prefix: [ICON_FOOD.Soup],
      leftSignature: LeftSignature.Alchemy,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x22e0',
      include: [
        'ekwd|ObjectTypeFood',
        'ekwd|IngredientTypeVegetable',
        'ekwd|MealTypeSoup',
      ],
      exclude: ['ekwd|IngredientTypeMeat'],
    },
    {
      order: 14,
      prefix: [ICON_FOOD.CannedFood],
      leftSignature: LeftSignature.Alchemy,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x22e1',
      include: ['ekwd|ObjectTypeFood', 'ekwd|MealTypePackaged'],
      exclude: ['ekwd|ObjectTypeCandy', 'ekwd|ObjectTypeCakesPies'],
    },
    {
      order: 15,
      prefix: [ICON_FOOD.Bubblegum],
      leftSignature: LeftSignature.Alchemy,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x22e2',
      include: ['edid|bubblegum'],
      exclude: [],
    },
    {
      order: 16,
      prefix: [ICON_FOOD.SnackCakes],
      leftSignature: LeftSignature.Alchemy,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x22e3',
      include: ['edid|FancyLadSnackCakes'],
      exclude: [],
    },
    {
      order: 17,
      prefix: [ICON_FOOD.SugarBombs],
      leftSignature: LeftSignature.Alchemy,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x22e4',
      include: ['edid|FancyLadSnackCakes'],
      exclude: [],
    },
    {
      order: 18,
      prefix: [ICON_FOOD.Candy],
      leftSignature: LeftSignature.Alchemy,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x22e5',
      include: ['ekwd|ObjectTypeCandy'],
      exclude: [],
    },
    {
      order: 19,
      prefix: [ICON_FOOD.Cake],
      leftSignature: LeftSignature.Alchemy,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x22e6',
      include: ['ekwd|ObjectTypeCakesPies'],
      exclude: ['ekwd|IngredientTypeMeat'],
    },
    {
      order: 20,
      prefix: [ICON_FOOD.BerryPie],
      leftSignature: LeftSignature.Alchemy,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: true,
      isFullReplaced: false,
      header: '0x22e7',
      include: [
        'edid|PumpkinPieTasty',
        'edid|PotholePotpie',
        'edid|CarnivalPie',
        'edid|MysteryMeatPieTasty',
        'edid|StarlightBerryCookedCobbler',
        'edid|MirelurkAndBloodleafGourmet',
        'edid|CranberryCookedCobbler',
        'edid|SheepsquatchMeatTasty',
      ],
      exclude: [],
    },
    {
      order: 21,
      prefix: [ICON_FOOD.MeatSoup],
      leftSignature: LeftSignature.Alchemy,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: true,
      isFullReplaced: false,
      header: '0x22e8',
      include: [
        'edid|GulperMeatCooked',
        'edid|RadStagMeatTastyStew',
        'edid|ScorchBeastTastyStew',
        'edid|StingwingMeatTastyStew',
        'edid|VenisonAndTatoStew_Psycho',
        'edid|VenisonAndTatoStew_Spiced',
        'edid|ChickenMeatCookedSoup',
      ],
      exclude: [],
    },
    {
      order: 22,
      prefix: [ICON_FOOD.CookedMeat],
      leftSignature: LeftSignature.Alchemy,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x22e9',
      include: [
        'ekwd|ObjectTypeFood',
        'ekwd|IngredientTypeMeat',
        'ekwd|MealTypeCooked',
      ],
      exclude: ['ekwd|MealTypeSoup'],
    },
    {
      order: 23,
      prefix: [ICON_FOOD.RawMeat],
      leftSignature: LeftSignature.Alchemy,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x22ea',
      include: ['ekwd|ObjectTypeFood', 'ekwd|IngredientTypeMeat'],
      exclude: [
        'ekwd|MealTypeCooked',
        'edid|MirelurkEgg',
        'edid|DeathclawEgg',
        'edid|MothmanEgg',
        'edid|RadToadEgg',
        'edid|RadscorpionEgg',
      ],
    },
    {
      order: 24,
      prefix: [ICON_FOOD.Egg],
      leftSignature: LeftSignature.Alchemy,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: true,
      isFullReplaced: false,
      header: '0x22eb',
      include: [
        'edid|MirelurkEgg',
        'edid|DeathclawEgg',
        'edid|MothmanEgg',
        'edid|RadToadEgg',
        'edid|RadscorpionEgg',
      ],
      exclude: [],
    },
    {
      order: 25,
      prefix: [ICON_FOOD.TickBlood],
      leftSignature: LeftSignature.Alchemy,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x22ec',
      include: ['edid|TickBlood'],
      exclude: [],
    },
    {
      order: 26,
      prefix: [ICON_FOOD.Berry],
      leftSignature: LeftSignature.Alchemy,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: true,
      isFullReplaced: false,
      header: '0x22ed',
      include: ['ekwd|PlantTypeBerry'],
      exclude: [],
    },
    {
      order: 27,
      prefix: [ICON_FOOD.Carrot],
      leftSignature: LeftSignature.Alchemy,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: true,
      isFullReplaced: false,
      header: '0x22ee',
      include: [
        'ekwd|PlantTypeVegetable',
        'ekwd|PlantTypeGourd',
        'ekwd|PlantTypeMelon',
      ],
      exclude: ['ekwd|PlantTypeFlowers'],
    },
    {
      order: 28,
      prefix: [ICON_FOOD.Flower],
      leftSignature: LeftSignature.Alchemy,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: true,
      isFullReplaced: false,
      header: '0x22ef',
      include: [
        'ekwd|ObjectTypeFlowers',
        'ekwd|PlantTypeAster',
        'ekwd|PlantTypeStranglerHerb',
      ],
      exclude: [],
    },
    {
      order: 29,
      prefix: [ICON_FOOD.Fruit],
      leftSignature: LeftSignature.Alchemy,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x22f0',
      include: ['edid|MutfruitFruit'],
      exclude: [],
    },
    {
      order: 30,
      prefix: [ICON_FOOD.Mushrooms],
      leftSignature: LeftSignature.Alchemy,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: true,
      isFullReplaced: false,
      header: '0x22f1',
      include: [
        'edid|BlightVegetable',
        'edid|BrainFungusVegetable',
        'edid|GutShroomVegetable',
        'edid|CaveFungusVegetable',
        'edid|GlowingFungusVegetable',
        'edid|MegaSlothMushroomVegetable',
        'edid|FirecapVegetable',
      ],
      exclude: ['ekwd|MealTypeCooked'],
    },
    {
      order: 31,
      prefix: [ICON_FOOD.Honey],
      leftSignature: LeftSignature.Alchemy,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x22f2',
      include: ['edid|honey'],
      exclude: ['ekwd|DrinkTypeAlcohol', 'ekwd|ObjectTypeCandy'],
    },
    {
      order: 32,
      prefix: [ICON_FOOD.Flavor],
      leftSignature: LeftSignature.Alchemy,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x22f3',
      include: ['ekwd|IngredientTypeFlavor'],
      exclude: [],
    },
  ],
} as const satisfies RulesGroup<ICON_FOOD>;
