import { ICON_HEAVY_WEAPONS } from "@/generated/icons-enum";
import { LeftSignature, RightSignature } from "@/constants";
import type { RulesGroup } from "@/types";
import { ICON_CATEGORIES } from "@/generated/icon-categories-enum";
export const HEAVY_WEAPONS_RULES_GROUP = {
    category: ICON_CATEGORIES.HeavyWeapons,
    rules: [
        {
            order: 0,
            prefix: [ICON_HEAVY_WEAPONS.Flamer],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|WeaponTypeFlamer"],
            exclude: [],
        },
        {
            order: 1,
            prefix: [ICON_HEAVY_WEAPONS.Cryolator],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|WeaponTypeCryolator"],
            exclude: [],
        },
        {
            order: 2,
            prefix: [ICON_HEAVY_WEAPONS.MachineGun],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|50calMachineGun"],
            exclude: [],
        },
        {
            order: 3,
            prefix: [ICON_HEAVY_WEAPONS.LightMachineGun],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|mg42"],
            exclude: [],
        },
        {
            order: 4,
            prefix: [ICON_HEAVY_WEAPONS.GatlingLaser],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|GatlingLaser"],
            exclude: [],
        },
        {
            order: 5,
            prefix: [ICON_HEAVY_WEAPONS.GatlingPlasma],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|GatlingPlasma"],
            exclude: ["ekwd|GatlingLaser"],
        },
        {
            order: 6,
            prefix: [ICON_HEAVY_WEAPONS.GatlingGun],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|GatlingGun"],
            exclude: [],
        },
        {
            order: 7,
            prefix: [ICON_HEAVY_WEAPONS.PlasmaCaster],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|PlasmaCaster"],
            exclude: [],
        },
        {
            order: 8,
            prefix: [ICON_HEAVY_WEAPONS.Minigun],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|minigun"],
            exclude: [],
        },
        {
            order: 9,
            prefix: [ICON_HEAVY_WEAPONS.Broadsider],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|broadsider"],
            exclude: [],
        },
        {
            order: 10,
            prefix: [ICON_HEAVY_WEAPONS.MissileLauncher],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|MissileLauncher"],
            exclude: [],
        },
        {
            order: 11,
            prefix: [ICON_HEAVY_WEAPONS.HellstormMissileLauncher],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|BOSRocketLauncher"],
            exclude: [],
        },
        {
            order: 12,
            prefix: [ICON_HEAVY_WEAPONS.GrenadeLauncher],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|m79"],
            exclude: [],
        },
        {
            order: 13,
            prefix: [ICON_HEAVY_WEAPONS.AutoGrenadeLauncher],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|GrenadeLauncher"],
            exclude: ["ekwd|m79"],
        },
        {
            order: 14,
            prefix: [ICON_HEAVY_WEAPONS.Fatman],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|fatman"],
            exclude: [],
        },
        {
            order: 15,
            prefix: [ICON_HEAVY_WEAPONS.HarpoonGun],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|HarpoonGun"],
            exclude: [],
        },
        {
            order: 16,
            prefix: [ICON_HEAVY_WEAPONS.JunkJet],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|JunkJet"],
            exclude: [],
        }
    ],
} as const satisfies RulesGroup<ICON_HEAVY_WEAPONS>;
