import { ICON_MELEE_WEAPONS } from "@/generated/icons-enum";
import { LeftSignature, RightSignature } from "@/constants";
import type { RulesGroup } from "@/types";
import { ICON_CATEGORIES } from "@/generated/icon-categories-enum";
export const MELEE_WEAPONS_RULES_GROUP = {
    category: ICON_CATEGORIES.MeleeWeapons,
    rules: [
        {
            order: 0,
            prefix: [ICON_MELEE_WEAPONS.PowerFist],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: ["edid|PowerFist", "edid|Gauntlet"],
            exclude: [],
        },
        {
            order: 1,
            prefix: [ICON_MELEE_WEAPONS.Unarmed],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|WeaponTypeUnarmed"],
            exclude: ["edid|PowerFist", "edid|Gauntlet"],
        },
        {
            order: 2,
            prefix: [ICON_MELEE_WEAPONS.Chainsaw],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|chainsaw"],
            exclude: [],
        },
        {
            order: 3,
            prefix: [ICON_MELEE_WEAPONS.Shishkebab],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|shishkebab"],
            exclude: [],
        },
        {
            order: 4,
            prefix: [ICON_MELEE_WEAPONS.Ripper],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|ripper"],
            exclude: [],
        },
        {
            order: 5,
            prefix: [ICON_MELEE_WEAPONS.Knife],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|knife"],
            exclude: ["edid|Throwing_Knife"],
        },
        {
            order: 6,
            prefix: [ICON_MELEE_WEAPONS.Machete],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|machete"],
            exclude: [],
        },
        {
            order: 7,
            prefix: [ICON_MELEE_WEAPONS.OneHandedAxe],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|WeaponTypeAxe", "ekwd|WeaponTypeMelee1H"],
            exclude: [],
        },
        {
            order: 8,
            prefix: [ICON_MELEE_WEAPONS.OneHandedBat],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|WeaponTypeBlunt", "ekwd|WeaponTypeMelee1H"],
            exclude: [],
        },
        {
            order: 9,
            prefix: [ICON_MELEE_WEAPONS.OneHandedMelee],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|WeaponTypeMelee1H"],
            exclude: [],
        },
        {
            order: 10,
            prefix: [ICON_MELEE_WEAPONS.SuperSledge],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|SuperSledge"],
            exclude: [],
        },
        {
            order: 11,
            prefix: [ICON_MELEE_WEAPONS.TwoHandedBat],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|WeaponTypeBlunt", "ekwd|WeaponTypeMelee2H"],
            exclude: [],
        },
        {
            order: 12,
            prefix: [ICON_MELEE_WEAPONS.TwoHandedAxe],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|WeaponTypeAxe", "ekwd|WeaponTypeMelee2H"],
            exclude: [],
        },
        {
            order: 13,
            prefix: [ICON_MELEE_WEAPONS.TwoHandedSword],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|WeaponTypeSword", "ekwd|WeaponTypeMelee2H"],
            exclude: [],
        },
        {
            order: 14,
            prefix: [ICON_MELEE_WEAPONS.TwoHandedMelee],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|WeaponTypeMelee2H"],
            exclude: [],
        }
    ],
} as const satisfies RulesGroup<ICON_MELEE_WEAPONS>;
