import { ICON_MINES } from "@/generated/icons-enum";
import { LeftSignature, RightSignature } from "@/constants";
import type { RulesGroup } from "@/types";
import { ICON_CATEGORIES } from "@/generated/icon-categories-enum";
export const MINES_RULES_GROUP = {
    category: ICON_CATEGORIES.Mines,
    rules: [
        {
            order: 0,
            prefix: [ICON_MINES.CryoMine],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|CryoMine"],
            exclude: [],
        },
        {
            order: 1,
            prefix: [ICON_MINES.PlasmaMine],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|PlasmaMine"],
            exclude: [],
        },
        {
            order: 2,
            prefix: [ICON_MINES.PulseMine],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|PulseMine"],
            exclude: [],
        },
        {
            order: 3,
            prefix: [ICON_MINES.BottlecapMine],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|BottlecapMine"],
            exclude: [],
        },
        {
            order: 4,
            prefix: [ICON_MINES.NukeMine],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|NukeMine"],
            exclude: [],
        },
        {
            order: 5,
            prefix: [ICON_MINES.FragmentationMine],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|WeaponTypeMine"],
            exclude: [
                "edid|CryoMine",
                "edid|PlasmaMine",
                "edid|PulseMine",
                "edid|BottlecapMine",
                "edid|NukeMine",
            ],
        }
    ],
} as const satisfies RulesGroup<ICON_MINES>;
