import { ICON_MISC } from "@/generated/icons-enum";
import { LeftSignature, RightSignature } from "@/constants";
import type { RulesGroup } from "@/types";
import { ICON_CATEGORIES } from "@/generated/icon-categories-enum";
export const MISC_RULES_GROUP = {
    category: ICON_CATEGORIES.Misc,
    rules: [
        {
            order: 0,
            prefix: [ICON_MISC.LegendaryModule],
            leftSignature: LeftSignature.Misc,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: ["edid|miscmod", "edid|LegendaryModule"],
            exclude: [],
        },
        {
            order: 1,
            prefix: [ICON_MISC.LegendaryCore],
            leftSignature: LeftSignature.Currency,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|LegendaryCore"],
            exclude: [],
        },
        {
            order: 2,
            prefix: [ICON_MISC.TreasureNote],
            leftSignature: LeftSignature.Misc,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|Treasury_Note"],
            exclude: [],
        },
        {
            order: 3,
            prefix: [ICON_MISC.NukeCard],
            leftSignature: LeftSignature.Misc,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|ObjectTypeNukeKeycard"],
            exclude: [],
        },
        {
            order: 4,
            prefix: [ICON_MISC.RepairKit],
            leftSignature: LeftSignature.Utility,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: ["edid|RepairKit", "edid|ScrapToStash"],
            exclude: [],
        },
        {
            order: 5,
            prefix: [ICON_MISC.LegendaryModification],
            leftSignature: LeftSignature.Misc,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|LegendaryShard"],
            exclude: [],
        },
        {
            order: 6,
            prefix: [ICON_MISC.FluxMisc],
            leftSignature: LeftSignature.Misc,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|ObjectTypeFlux"],
            exclude: [],
        },
        {
            order: 7,
            prefix: [ICON_MISC.Token],
            leftSignature: LeftSignature.Misc,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|token"],
            exclude: [],
        },
        {
            order: 8,
            prefix: [ICON_MISC.Cards],
            leftSignature: LeftSignature.Misc,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|Moon_CryptidCardKeyword"],
            exclude: [],
        },
        {
            order: 9,
            prefix: [ICON_MISC.Bulk],
            leftSignature: LeftSignature.Misc,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|Bulk"],
            exclude: [],
        },
        {
            order: 10,
            prefix: [ICON_MISC.Components],
            leftSignature: LeftSignature.Misc,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|ObjectTypeComponent"],
            exclude: [],
        },
        {
            order: 11,
            prefix: [ICON_MISC.Corpse],
            leftSignature: LeftSignature.Misc,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "edid|Horn_Sheepsquatch",
                "edid|FloaterPusSac",
                "edid|WendigoColossus",
                "edid|RadscorpionStinger",
                "edid|BloatflyGland",
                "edid|AcidGulperGland",
                "edid|MoleRatTeeth",
                "edid|TickBloodSac",
                "edid|DeathclawHand",
                "edid|BloodbugProboscis",
                "edid|SheepsquatchSkull",
                "edid|StingwingBarb",
                "edid|BeaverTeeth",
                "edid|WendigoTeeth",
            ],
            exclude: [],
        },
        {
            order: 12,
            prefix: [ICON_MISC.Skull],
            leftSignature: LeftSignature.Misc,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|BoneTypeSkull"],
            exclude: [],
        },
        {
            order: 13,
            prefix: [ICON_MISC.Bones],
            leftSignature: LeftSignature.Misc,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|ObjectTypeBones"],
            exclude: ["ekwd|BoneTypeSkull"],
        },
        {
            order: 14,
            prefix: [ICON_MISC.TeddyBear],
            leftSignature: LeftSignature.Misc,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|ObjectTypeTeddyBear"],
            exclude: [],
        },
        {
            order: 15,
            prefix: [ICON_MISC.RocketToy],
            leftSignature: LeftSignature.Misc,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|ObjectTypeToy"],
            exclude: [],
        },
        {
            order: 16,
            prefix: [ICON_MISC.CircuitBoard],
            leftSignature: LeftSignature.Misc,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "edid|CircuitBoard",
                "edid|BiometricScanner",
                "edid|EyebotPart",
            ],
            exclude: [],
        },
        {
            order: 17,
            prefix: [ICON_MISC.Canister],
            leftSignature: LeftSignature.Misc,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|canister"],
            exclude: [],
        },
        {
            order: 18,
            prefix: [ICON_MISC.MetalScrap],
            leftSignature: LeftSignature.Misc,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "edid|TinCan",
                "edid|PaintCan",
                "edid|OilCan",
                "edid|SetCan",
                "edid|Fork",
            ],
            exclude: [],
        },
        {
            order: 19,
            prefix: [ICON_MISC.Ore],
            leftSignature: LeftSignature.Misc,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|_ore_"],
            exclude: [],
        },
        {
            order: 20,
            prefix: [ICON_MISC.Junk],
            leftSignature: LeftSignature.Misc,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [],
            exclude: ["edid|miscmod"],
        },
        {
            order: 21,
            prefix: [ICON_MISC.Quest],
            leftSignature: LeftSignature.Misc,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [],
            exclude: [],
        }
    ],
} as const satisfies RulesGroup<ICON_MISC>;
