import { ICON_NOTES } from "@/generated/icons-enum";
import { LeftSignature, RightSignature } from "@/constants";
import type { RulesGroup } from "@/types";
import { ICON_CATEGORIES } from "@/generated/icon-categories-enum";
export const NOTES_RULES_GROUP = {
    category: ICON_CATEGORIES.Notes,
    rules: [
        {
            order: 0,
            prefix: [ICON_NOTES.SiloTape],
            leftSignature: LeftSignature.Note,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|SiloStateTape"],
            exclude: [],
        },
        {
            order: 1,
            prefix: [ICON_NOTES.Plan, ICON_NOTES.PlanRare],
            leftSignature: LeftSignature.Book,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "edid|recipe_DLC04_mod_melee_BaseballBat_Heated",
                "edid|recipe_Headwear_CivilWarHatUnion",
                "edid|recipe_mod_melee_Shishkebab_ExtraFlameJets",
                "edid|recipe_Armor_VaultSuitVT_Underarmor",
                "edid|Recipe_Weapon_Ranged_LaserGun",
                "edid|recipe_Armor_Casual_Underarmor_ShirtJeans",
                "edid|Recipe_Weapon_Melee_ChineseOfficerSword",
                "edid|recipe_mod_melee_Powerfist_Heated",
                "edid|recipe_DLC03_mod_melee_polehook_Multihook",
                "edid|recipe_DLC04_mod_melee_BaseballBat_Rocket_SpikesLarge_Heated",
                "edid|recipe_DLC04_mod_melee_BaseballBat_Rocket",
                "edid|Recipe_Backpack_Standard_Material_Blueridge",
                "edid|recipe_mod_PowerArmor_Ultracite_Torso_Misc_BatRegen",
                "edid|recipe_Armor_Marine_Underarmor_Helmet",
                "edid|recipe_mod_melee_Ripper_BladesLarge",
                "edid|recipe_mod_PowerArmor_Ultracite_Torso_Misc_DMGShield",
                "edid|recipe_mod_PowerArmor_Ultracite_Leg_Misc_APRegen",
                "edid|Recipe_Weapon_Ranged_Ultracite_GatlingLaser",
                "edid|recipe_mod_PowerArmor_Ultracite_Torso_Misc_Cleanser",
                "edid|recipe_mod_PowerArmor_Ultracite_Torso_Misc_Kinetic",
                "edid|Recipe_Workshop_WallDecor_BRCCFlag01",
                "edid|recipe_Armor_Casual_Underarmor_FlannelJeans",
                "edid|recipe_Armor_BoS_Officer_Underarmor",
                "edid|recipe_Armor_BoS_Knight_Underarmor",
                "edid|recipe_Clothes_CivilWarUniformUnion",
                "edid|recipe_Clothes_CivilWarUniformConfederate",
                "edid|recipe_Armor_BoS_Soldier_Underarmor",
                "edid|recipe_mod_melee_ChineseOfficerSword_Shock",
                "edid|recipe_mod_melee_ChineseOfficerSword_ShockAndSerrated",
                // rare next
                "edid|recipe_mod_PowerArmor_Ultracite_Torso_Misc_Reactive",
                "edid|recipe_mod_melee_BoxingGlove_ExtraHeavyHead",
                "edid|Recipe_Weapon_Ranged_GatlingPlasma_Mag_Ammo",
                "edid|recipe_DLC03_mod_armor_Trapper_Lining_Torso_Explosion2",
                "edid|recipe_DLC03_miscmod_mod_armor_Marine_Lining_Torso_Explosion2",
                "edid|Recipe_Weapon_Ranged_GatlingPlasma_Mag_ReloadSpeed",
                "edid|Recipe_Weapon_Ranged_GatlingPlasma_Receiver_Burning",
                "edid|Recipe_Weapon_Ranged_GatlingPlasma_Mag_ArmorPen",
                "edid|recipe_mod_melee_Switchblade_Serrated",
                "edid|Recipe_Weapon_Ranged_GatlingPlasma_Receiver_CritDMG",
                "edid|recipe_Armor_PowerArmor_T60_LegLeft",
                "edid|recipe_Armor_PowerArmor_T60_ArmLeft",
                "edid|recipe_DLC04_mod_melee_DLC04_CommieWhacker_BladesLarge",
                "edid|recipe_mod_PowerArmor_T60_Material_Paint_BOSOfficer",
                "edid|recipe_mod_PowerArmor_T60_Material_Paint_BOSPaladin",
                "edid|recipe_mod_PowerArmor_T60_Material_Paint_BOSKnightCaptain",
                "edid|recipe_mod_PowerArmor_T60_Material_Paint_BOSKnight",
                "edid|recipe_mod_PowerArmor_T60_Material_Paint_BOSKnightSgt",
                "edid|recipe_mod_PowerArmor_T60_Material_Paint_BOSElder",
                "edid|recipe_Armor_PowerArmor_T60_LegRight",
                "edid|recipe_Armor_PowerArmor_T60_ArmRight",
                "edid|recipe_mod_DoubleBarrelShotgun_Receiver_ScorchedKiller",
                "edid|recipe_mod_LeverGun_Receiver_ScorchedKiller",
                "edid|recipe_mod_melee_Machete_Sacrificial",
                "edid|recipe_DLC04_mod_melee_Sledgehammer_ExtraHeavyHead_Rocket_Blades_Heated",
                "edid|recipe_DLC04_mod_melee_Sledgehammer_ExtraHeavyHead_Rocket_Blades",
                "edid|recipe_DLC04_mod_melee_Sledgehammer_ExtraHeavyHead_Rocket_Spikes",
                "edid|recipe_mod_PowerArmor_Ultracite_Leg_Misc_OptimizedServos",
                "edid|recipe_mod_PowerArmor_Ultracite_Leg_Misc_SprintBoost",
                "edid|recipe_mod_PowerArmor_Ultracite_Torso_Misc_Tesla",
                "edid|recipe_mod_PowerArmor_Ultracite_Torso_Misc_Emergency",
                "edid|recipe_mod_PowerArmor_Ultracite_Leg_Misc_Carry",
                "edid|recipe_mod_PowerArmor_Ultracite_Helmet_Misc_DetectLife",
                "edid|Recipe_Weapon_Ranged_GatlingPlasma_Muzzle_Fast",
                "edid|recipe_Armor_PowerArmor_T60_Helmet",
                "edid|recipe_mod_armor_UnderArmor_Casual_Mk5",
            ],
            exclude: [],
        },
        {
            order: 2,
            prefix: [ICON_NOTES.Plan, ICON_NOTES.PlanBigFish],
            leftSignature: LeftSignature.Book,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|Fishing_Workshop"],
            exclude: [],
        },
        {
            order: 3,
            prefix: [ICON_NOTES.Plan, ICON_NOTES.PlanGrahm],
            leftSignature: LeftSignature.Book,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "edid|Recipe_Workshop_Benches_Stone",
                "edid|Recipe_Workshop_WallDecor_WallClocks_Starburst",
                "edid|Recipe_Workshop_Benches_Wood_Park",
                "edid|Recipe_Workshop_Lights_MirrorBall01",
                "edid|Recipe_Workshop_Tables_PlayerHouse_Ruin_Kitchen",
                "edid|Recipe_Workshop_Tables_NpcTableVaultSit02",
                "edid|Recipe_Workshop_Trap_Radiation",
            ],
            exclude: [],
        },
        {
            order: 4,
            prefix: [ICON_NOTES.Plan, ICON_NOTES.PlanGrahm, ICON_NOTES.PlanYearTwentyThree],
            leftSignature: LeftSignature.Book,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "edid|Recipe_Workshop_Benches_Wood_CleanPark",
                "edid|Recipe_Workshop_Tables_DomesticKitchen_Brown",
                "edid|Recipe_Workshop_Tables_DomesticKitchen_Black",
                "edid|Recipe_Workshop_Tables_DomesticKitchen_White",
                "edid|Recipe_Workshop_Container_Prewar_Suitcase_Clothes_Clean_Purple",
                "edid|Recipe_Workshop_Lights_MirrorBall_Blue",
                "edid|Recipe_Workshop_Container_Prewar_Suitcase_Clothes_Clean_Black",
                "edid|Recipe_Workshop_Container_Prewar_Suitcase_Clothes_Clean_Blue",
                "edid|Recipe_Workshop_Container_Prewar_Suitcase_Clothes_Clean_Green",
                "edid|Recipe_Workshop_Container_Prewar_Suitcase_Clothes_Clean_Pink",
                "edid|Recipe_Workshop_Container_Prewar_Suitcase_Clothes_Clean_Yellow",
                "edid|Recipe_Workshop_Container_Prewar_Suitcase_Clothes_Clean_Red",
                "edid|Recipe_Workshop_Lights_MirrorBall_Pink",
                "edid|Recipe_Workshop_Container_Prewar_Suitcase_Clothes_Clean_Orange",
                "edid|Recipe_Workshop_Lights_MirrorBall_Green",
                "edid|Recipe_Workshop_Lights_MirrorBall_Red",
                "edid|Recipe_Workshop_Tables_MetalPicnic_Pink",
                "edid|Recipe_Workshop_Tables_MetalPicnic_Green",
                "edid|Recipe_Workshop_Tables_MetalPicnic_White",
                "edid|Recipe_Workshop_Tables_MetalPicnic_Blue",
                "edid|Recipe_Workshop_Tables_MetalPicnic_Red",
            ],
            exclude: [],
        },
        {
            order: 5,
            prefix: [ICON_NOTES.Plan, ICON_NOTES.PlanAlien, ICON_NOTES.PlanYearTwentyFive],
            leftSignature: LeftSignature.Book,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|Recipe_Invaders_Workshop_Arcade_AlienWhackAMole"],
            exclude: [],
        },
        {
            order: 6,
            prefix: [ICON_NOTES.Plan, ICON_NOTES.PlanAlien, ICON_NOTES.PlanYearTwentyFour, ICON_NOTES.PlanQFour],
            leftSignature: LeftSignature.Book,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "edid|Invaders_Recipe_Workshop_FloorDecor_FuturisticGlobe",
                "edid|Invaders_Recipe_workshop_Furniture_Couch_AlienCouch",
                "edid|Invaders_Recipe_FloorDecor_NukaDarkRocket",
                "edid|Invaders_Recipe_FloorDecor_NukaGrapeRocket",
                "edid|Invaders_Recipe_FloorDecor_NukaCherryRocket",
                "edid|Invaders_Recipe_FloorDecor_NukaQuantumRocket",
                "edid|Invaders_Recipe_FloorDecor_NukaTwistRocket",
                "edid|Invaders_Recipe_FloorDecor_NukaColaRocket",
                "edid|Invaders_Recipe_Armor_HazmatSuit_Pink",
            ],
            exclude: [],
        },
        {
            order: 7,
            prefix: [ICON_NOTES.Plan, ICON_NOTES.PlanAlien, ICON_NOTES.PlanYearTwentyFour],
            leftSignature: LeftSignature.Book,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "edid|Recipe_Invaders_AlienBlaster_Refined",
                "edid|Recipe_Invaders_Armor_HazmatSuitTeal",
                "edid|Recipe_Invaders_Workshop_Lights_AlienHeadLamp",
                "edid|Recipe_Invaders_Workshop_Tables_AlienTable",
                "edid|Recipe_Invaders_Workshop_Lights_GlowingFlatwoodsMonsterLamp",
                "edid|Recipe_Invaders_Workshop_WallDecor_AlienTargetPracticePoster",
            ],
            exclude: [],
        },
        {
            order: 8,
            prefix: [ICON_NOTES.Plan, ICON_NOTES.PlanAlien],
            leftSignature: LeftSignature.Book,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "edid|POST_recipe_mod_AlienBlaster_Scope_ScopeShort_NV",
                "edid|recipe_mod_AlienBlaster_AlienMag_AmmoConversion",
                "edid|Recipe_Weapon_Ranged_AlienBlaster",
                "edid|Recipe_Workshop_ZetanTube",
                "edid|recipe_mod_AlienBlaster_AlienMag_DTPoison",
                "edid|recipe_mod_AlienBlaster_AlienMag_DTCryo",
                "edid|Recipe_Weapon_Ranged_AlienRifle",
                "edid|recipe_mod_AlienRifle_Receiver_DTCryo",
                "edid|recipe_mod_AlienRifle_Receiver_DTPoison",
                "edid|recipe_mod_AlienRifle_Receiver_Sniper",
                "edid|recipe_mod_AlienRifle_Receiver_Auto",
                "edid|Recipe_mod_melee_ElectroEnforcer_Spiked",
                "edid|Recipe_Weapon_Melee_ElectroEnforcer",
                "edid|Recipe_mod_melee_ElectroEnforcer_Overcharged",
                "edid|Recipe_mod_melee_ElectroEnforcer_Poisoned",
                "edid|Recipe_mod_melee_ElectroEnforcer_Freezing",
                "edid|Recipe_Workshop_AlienOperatingBed",
                "edid|Recipe_Workshop_Container_StashBox_Zetan",
                "edid|Recipe_Workshop_FloorDecor_Asteroid",
                "edid|Recipe_Workshop_HumanMaleTube",
                "edid|Recipe_Workshop_HumanFemaleTube",
            ],
            exclude: [],
        },
        {
            order: 9,
            prefix: [ICON_NOTES.Plan, ICON_NOTES.PlanMothman, ICON_NOTES.PlanYearTwentyFour, ICON_NOTES.PlanQThree],
            leftSignature: LeftSignature.Book,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "edid|E07A_Recipe_Headwear_BoneChillSkullMask",
                "edid|E07A_Recipe_Headwear_HammeredSkullMask",
                "edid|E07A_Recipe_Headwear_CrudeSkullMask",
                "edid|E07A_Recipe_Workshop_Displays_MothsOfWestVirginiaCabinet",
                "edid|E07A_Recipe_Tinkers_Souvenir_Moths_LunaMoth",
                "edid|E07A_Recipe_Tinkers_Souvenir_Moths_VirginiaCreeper",
                "edid|E07A_Recipe_Tinkers_Souvenir_Moths_IoMoth",
                "edid|E07A_Recipe_Tinkers_Souvenir_Moths_AmericanDaggerMoth",
                "edid|E07A_Recipe_Tinkers_Souvenir_Moths_BeautifulWoodNymphMoth",
                "edid|E07A_Recipe_Tinkers_Souvenir_Moths_GiantLeopardMoth",
                "edid|E07A_Recipe_Workshop_Displays_MothsOfWestVirginiaBoard",
            ],
            exclude: [],
        },
        {
            order: 10,
            prefix: [ICON_NOTES.Plan, ICON_NOTES.PlanMothman, ICON_NOTES.PlanYearTwentyFour],
            leftSignature: LeftSignature.Book,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "edid|E07A_Recipe_workshop_FloorDecor_MothVFX",
                "edid|E07A_Recipe_Headwear_CultistNeophyte",
                "edid|E07A_Recipe_Headwear_CultistIncarnateHelmet",
                "edid|E07A_Recipe_Clothes_CultistAdept",
                "edid|E07A_Recipe_Clothes_CultistEnlightened",
                "edid|E07A_Recipe_Headwear_CultistEventide",
                "edid|E07A_Recipe_Clothes_CultistEventide",
                "edid|E07A_Recipe_Headwear_CultistAdept",
                "edid|E07A_Recipe_Headwear_CultistEnlightened",
                "edid|E07A_Recipe_WallDecor_DriedFLowers",
                "edid|E07A_Recipe_Clothes_CultistNeophyte",
                "edid|E07A_recipe_Workshop_Incense_MothmanCultist",
                "edid|Recipe_Workshop_CeilingDecor_Honeycomb_Paper_GreenMothman",
                "edid|Recipe_Workshop_CeilingDecor_Honeycomb_Paper_BlueMothman",
                "edid|Recipe_Workshop_CeilingDecor_Honeycomb_Paper_RedMothman",
                "edid|Recipe_Workshop_CeilingDecor_Honeycomb_Paper_BrownMothman",
                "edid|Recipe_Workshop_CeilingDecor_Honeycomb_Paper_MothmanGlobe",
                "edid|E07A_Recipe_Plushie_FuzzyMothman",
                "edid|Recipe_Workshop_FloorDecor_Mothman_EnlightenedLantern",
                "edid|E07A_Mothman_Bugzapper_Mothman",
                "edid|E07A_Recipe_Furniture_SacredMothmanTome",
                "edid|Recipe_mod_Chainsaw_Paint_Skeptikill",
                "edid|E07A_Recipe_Plushie_FuzzyEnlightened",
            ],
            exclude: [],
        },
        {
            order: 11,
            prefix: [ICON_NOTES.Plan, ICON_NOTES.PlanMothman],
            leftSignature: LeftSignature.Book,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "edid|E07A_Mothman_WiseMothman_Throne",
                "edid|E07A_Recipe_Backpack_Standard_Material_Cultist",
            ],
            exclude: [],
        },
        {
            order: 12,
            prefix: [ICON_NOTES.Plan, ICON_NOTES.PlanBlueDevil],
            leftSignature: LeftSignature.Book,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "edid|MOON_Herd_Workshop_Recipe_PaddockFence",
                "edid|MOON_Herd_Workshop_Recipe_BlueDevilOutfit",
                "edid|MOON_Herd_Workshop_Recipe_BlueDevilHood",
                "edid|Moon_Herd_Workshop_Recipe_BlueDevilTrophy",
                "edid|MOON_Herd_Workshop_Recipe_TaxidermyBlueDevil",
                "edid|MOON_Herd_Workshop_Recipe_CurtainBlueDevil",
                "edid|MOON_Herd_Workshop_Recipe_BrahminBackpack",
                "edid|MOON_Herd_Workshop_Recipe_BlueDevilPlushie",
                "edid|MOON_Herd_Workshop_Recipe_KidsCowClock",
                "edid|MOON_Herd_Workshop_Recipe_CartographyTable",
                "edid|MOON_Herd_Workshop_Recipe_TrailerTruckGear",
                "edid|MOON_Herd_Workshop_Recipe_BlueDevilFlair",
                "edid|MOON_Herd_Workshop_Recipe_Milkman",
                "edid|MOON_Herd_Workshop_Recipe_MilkmanHat",
                "edid|MOON_Herd_Workshop_Recipe_BrahminPlushie",
                "edid|MOON_Herd_Workshop_Recipe_PaddockGate",
                "edid|Moon_Recipe_Workshop_FloorDecor_Rugs_BrahminRug",
                "edid|MOON_Herd_Workshop_Recipe_Rug",
                "edid|MOON_Herd_Workshop_Recipe_TravellersWagon",
            ],
            exclude: [],
        },
        {
            order: 13,
            prefix: [ICON_NOTES.Plan, ICON_NOTES.PlanOgua],
            leftSignature: LeftSignature.Book,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "edid|MOON_Herd_Workshop_Recipe_OguaHunterHood",
                "edid|MOON_Herd_Workshop_Recipe_OguaHunterOutfit",
                "edid|MOON_Ambush_Recipe_OguaShellBackpack",
                "edid|MOON_Ambush_Workshop_Recipe_SleepingBag",
                "edid|MOON_Ambush_Workshop_Recipe_BlueRidgeScoutOutfit",
                "edid|MOON_Ambush_Workshop_Recipe_CurtainOgua",
                "edid|Moon_Ambush_Workshop_Recipe_OguaTrophy",
                "edid|MOON_Ambush_Workshop_Recipe_OguaPlushie",
                "edid|MOON_Ambush_Workshop_Recipe_SleepingBagFur",
                "edid|MOON_Ambush_Workshop_Recipe_OguaFlair",
                "edid|MOON_Ambush_Workshop_Recipe_Tent",
                "edid|MOON_Ambush_Workshop_Recipe_CryptidHunterBoonieHat",
                "edid|MOON_Ambush_Workshop_Recipe_Mobile",
                "edid|MOON_Ambush_Workshop_Recipe_OguaEgg",
            ],
            exclude: [],
        },
        {
            order: 14,
            prefix: [ICON_NOTES.Plan, ICON_NOTES.PlanEmpty],
            leftSignature: LeftSignature.Book,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|ObjectTypeRecipe"],
            exclude: [],
        },
        {
            order: 15,
            prefix: [ICON_NOTES.TreasureMap],
            leftSignature: LeftSignature.Book,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|TreasureMap"],
            exclude: [],
        },
        {
            order: 16,
            prefix: [ICON_NOTES.Note],
            leftSignature: LeftSignature.Book,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [],
            exclude: ["ekwd|ObjectTypeRecipe", "ekwd|MagazineKeyword"],
        },
        {
            order: 17,
            prefix: [ICON_NOTES.Holotape],
            leftSignature: LeftSignature.Note,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: true,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [],
            exclude: [],
        },
        {
            order: 18,
            prefix: [ICON_NOTES.Holotape],
            leftSignature: LeftSignature.Note,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|Storm_MQ03_OberlinsHolotape"],
            exclude: [],
        },
        {
            order: 19,
            prefix: [ICON_NOTES.Check],
            leftSignature: LeftSignature.Book,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [],
            exclude: [],
            translationReplacing: ["$Known", "$KNOWN"],
        }
    ],
} as const satisfies RulesGroup<ICON_NOTES>;
