import { ICON_PISTOLS } from '@/generated/icons-enum';
import { LeftSignature, RightSignature } from '@/constants';
import type { RulesGroup } from '@/types';
import { ICON_CATEGORIES } from '@/generated/icon-categories-enum';

export const PISTOLS_RULES_GROUP = {
  category: ICON_CATEGORIES.Pistols,
  rules: [
    {
      order: 0,
      iconName: ICON_PISTOLS.GaussPistol,
      leftSignature: LeftSignature.Weapon,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x233e',
      include: ['edid|GaussPistol'],
      exclude: [],
    },
    {
      order: 1,
      iconName: ICON_PISTOLS.AlienBluster,
      leftSignature: LeftSignature.Weapon,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x233f',
      include: ['edid|AlienBlaster'],
      exclude: [],
    },
    {
      order: 2,
      iconName: ICON_PISTOLS.GammaGun,
      leftSignature: LeftSignature.Weapon,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x2340',
      include: ['edid|GammaGun'],
      exclude: [],
    },
    {
      order: 3,
      iconName: ICON_PISTOLS.PlasmaPistol,
      leftSignature: LeftSignature.Weapon,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x2341',
      include: [],
      exclude: [],
    },
    {
      order: 4,
      iconName: ICON_PISTOLS.LaserPistol,
      leftSignature: LeftSignature.Weapon,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x2342',
      include: [],
      exclude: [],
    },
    {
      order: 5,
      iconName: ICON_PISTOLS.Revolver,
      leftSignature: LeftSignature.Weapon,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: true,
      isFullReplaced: false,
      header: '0x2343',
      include: ['edid|revolver', 'edid|44'],
      exclude: [],
    },
    {
      order: 6,
      iconName: ICON_PISTOLS.PipeRevolver,
      leftSignature: LeftSignature.Weapon,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x2344',
      include: [],
      exclude: [],
    },
    {
      order: 7,
      iconName: ICON_PISTOLS.PipePistol,
      leftSignature: LeftSignature.Weapon,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x2345',
      include: ['edid|PipeBoltAction'],
      exclude: [],
    },
    {
      order: 8,
      iconName: ICON_PISTOLS.FlareGun,
      leftSignature: LeftSignature.Weapon,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x2346',
      include: ['edid|FlareGun'],
      exclude: [],
    },
    {
      order: 9,
      iconName: ICON_PISTOLS.CrusaderPistol,
      leftSignature: LeftSignature.Weapon,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x2347',
      include: ['edid|BoSPistol'],
      exclude: [],
    },
    {
      order: 10,
      iconName: ICON_PISTOLS.ThirstZapper,
      leftSignature: LeftSignature.Weapon,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x2348',
      include: ['edid|ThirstZapper'],
      exclude: [],
    },
    {
      order: 11,
      iconName: ICON_PISTOLS.BlackPowderPistol,
      leftSignature: LeftSignature.Weapon,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x2349',
      include: ['edid|BlackPowder_Pistol'],
      exclude: [],
    },
  ],
} as const satisfies RulesGroup<ICON_PISTOLS>;
