import { ICON_PISTOLS } from "@/generated/icons-enum";
import { LeftSignature, RightSignature } from "@/constants";
import type { RulesGroup } from "@/types";
import { ICON_CATEGORIES } from "@/generated/icon-categories-enum";
export const PISTOLS_RULES_GROUP = {
    category: ICON_CATEGORIES.Pistols,
    rules: [
        {
            order: 0,
            prefix: [ICON_PISTOLS.GaussPistol],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|GaussPistol"],
            exclude: [],
        },
        {
            order: 1,
            prefix: [ICON_PISTOLS.AlienBluster],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|AlienBlaster"],
            exclude: [],
        },
        {
            order: 2,
            prefix: [ICON_PISTOLS.GammaGun],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|GammaGun"],
            exclude: [],
        },
        {
            order: 3,
            prefix: [ICON_PISTOLS.PlasmaPistol],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [],
            exclude: [],
        },
        {
            order: 4,
            prefix: [ICON_PISTOLS.LaserPistol],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [],
            exclude: [],
        },
        {
            order: 5,
            prefix: [ICON_PISTOLS.Revolver],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: ["edid|revolver", "edid|44"],
            exclude: [],
        },
        {
            order: 6,
            prefix: [ICON_PISTOLS.PipeRevolver],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [],
            exclude: [],
        },
        {
            order: 7,
            prefix: [ICON_PISTOLS.PipePistol],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|PipeBoltAction"],
            exclude: [],
        },
        {
            order: 8,
            prefix: [ICON_PISTOLS.FlareGun],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|FlareGun"],
            exclude: [],
        },
        {
            order: 9,
            prefix: [ICON_PISTOLS.CrusaderPistol],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|BoSPistol"],
            exclude: [],
        },
        {
            order: 10,
            prefix: [ICON_PISTOLS.ThirstZapper],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|ThirstZapper"],
            exclude: [],
        },
        {
            order: 11,
            prefix: [ICON_PISTOLS.BlackPowderPistol],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|BlackPowder_Pistol"],
            exclude: [],
        }
    ],
} as const satisfies RulesGroup<ICON_PISTOLS>;
