import { ICON_RIFLES } from '@/generated/icons-enum';
import { LeftSignature, RightSignature } from '@/constants';
import type { RulesGroup } from '@/types';
import { ICON_CATEGORIES } from '@/generated/icon-categories-enum';

export const RIFLES_RULES_GROUP = {
  category: ICON_CATEGORIES.Rifles,
  rules: [
    {
      order: 0,
      prefix: [ICON_RIFLES.Fixer],
      leftSignature: LeftSignature.Weapon,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x2332',
      include: ['edid|fixer'],
      exclude: [],
    },
    {
      order: 1,
      prefix: [ICON_RIFLES.HandmadeRifle],
      leftSignature: LeftSignature.Weapon,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x2333',
      include: ['edid|HandmadeRifle'],
      exclude: [],
    },
    {
      order: 2,
      prefix: [ICON_RIFLES.RailwayRifle],
      leftSignature: LeftSignature.Weapon,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x2334',
      include: ['edid|RailwayRifle'],
      exclude: [],
    },
    {
      order: 3,
      prefix: [ICON_RIFLES.TeslaRifle],
      leftSignature: LeftSignature.Weapon,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x2335',
      include: ['edid|LightningGun'],
      exclude: [],
    },
    {
      order: 4,
      prefix: [ICON_RIFLES.AlienDisintegrator],
      leftSignature: LeftSignature.Weapon,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x2336',
      include: ['edid|AlienRifle'],
      exclude: [],
    },
    {
      order: 5,
      prefix: [ICON_RIFLES.GaussRifle],
      leftSignature: LeftSignature.Weapon,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x2337',
      include: ['edid|GaussRifle'],
      exclude: [],
    },
    {
      order: 6,
      prefix: [ICON_RIFLES.PlasmaRifle],
      leftSignature: LeftSignature.Weapon,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x2338',
      include: ['edid|PlasmaGun'],
      exclude: [],
    },
    {
      order: 7,
      prefix: [ICON_RIFLES.LaserRifle],
      leftSignature: LeftSignature.Weapon,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x2339',
      include: ['edid|LaserGun'],
      exclude: [],
    },
    {
      order: 8,
      prefix: [ICON_RIFLES.PipeRifle],
      leftSignature: LeftSignature.Weapon,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x233a',
      include: ['edid|PipeGun'],
      exclude: [],
    },
    {
      order: 9,
      prefix: [ICON_RIFLES.LaserMusket],
      leftSignature: LeftSignature.Weapon,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x233b',
      include: ['edid|LaserMusket'],
      exclude: [],
    },
    {
      order: 10,
      prefix: [ICON_RIFLES.Rifle],
      leftSignature: LeftSignature.Weapon,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x233c',
      include: ['ekwd|WeaponTypeRifle'],
      exclude: [
        'edid|fixer',
        'edid|HandmadeRifle',
        'edid|RailwayRifle',
        'edid|LightningGun',
        'edid|AlienRifle',
        'edid|GaussRifle',
        'edid|PlasmaGun',
        'edid|LaserGun',
        'edid|PipeGun',
        'edid|LaserMusket',
        'edid|WesternSpirit',
      ],
    },
  ],
} as const satisfies RulesGroup<ICON_RIFLES>;
