import { ICON_THROWN_WEAPONS } from '@/generated/icons-enum';
import { LeftSignature, RightSignature } from '@/constants';
import type { RulesGroup } from '@/types';
import { ICON_CATEGORIES } from '@/generated/icon-categories-enum';

export const THROWN_WEAPONS_RULES_GROUP = {
  category: ICON_CATEGORIES.ThrownWeapons,
  rules: [
    {
      order: 0,
      prefix: [ICON_THROWN_WEAPONS.MeatClever],
      leftSignature: LeftSignature.Weapon,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x2267',
      include: ['ekwd|ThrowingKnife'],
      exclude: [],
    },
    {
      order: 1,
      prefix: [ICON_THROWN_WEAPONS.NukaGrenade],
      leftSignature: LeftSignature.Weapon,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x2268',
      include: ['edid|NukaGrenade'],
      exclude: [],
    },
    {
      order: 2,
      prefix: [ICON_THROWN_WEAPONS.PlasmaGrenade],
      leftSignature: LeftSignature.Weapon,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x2269',
      include: ['edid|PlasmaGrenade'],
      exclude: [],
    },
    {
      order: 3,
      prefix: [ICON_THROWN_WEAPONS.CryoGrenade],
      leftSignature: LeftSignature.Weapon,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x226a',
      include: ['edid|CryoGrenade'],
      exclude: [],
    },
    {
      order: 4,
      prefix: [ICON_THROWN_WEAPONS.PulseGrenade],
      leftSignature: LeftSignature.Weapon,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x226b',
      include: ['edid|PulseGrenade'],
      exclude: [],
    },
    {
      order: 5,
      prefix: [ICON_THROWN_WEAPONS.FragmentationGrenade],
      leftSignature: LeftSignature.Weapon,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x226c',
      include: ['ekwd|WeaponTypeGrenade'],
      exclude: [
        'edid|PulseGrenade',
        'edid|NukaGrenade',
        'edid|SuiciderBomb',
        'edid|PlasmaGrenade',
        'edid|CryoGrenade',
        'edid|dynamite',
        'edid|m79',
        'ekwd|ThrowingKnife',
      ],
    },
    {
      order: 6,
      prefix: [ICON_THROWN_WEAPONS.ThrownBomb],
      leftSignature: LeftSignature.Weapon,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: true,
      isFullReplaced: false,
      header: '0x226d',
      include: ['edid|SuiciderBomb', 'edid|TurboFertFertilizer'],
      exclude: [],
    },
    {
      order: 7,
      prefix: [ICON_THROWN_WEAPONS.Dynamite],
      leftSignature: LeftSignature.Weapon,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x226e',
      include: ['edid|dynamite'],
      exclude: [],
    },
  ],
} as const satisfies RulesGroup<ICON_THROWN_WEAPONS>;
