import { ICON_UTILITY } from "@/generated/icons-enum";
import type { RulesGroup } from "@/types";
import { ICON_CATEGORIES } from "@/generated/icon-categories-enum";
import { LeftSignature, RightSignature } from "@/constants";
const notExistedEdid = "edid|absolutely_not_existed_edid" as const;
export const UTILITY_RULES_GROUP = {
    category: ICON_CATEGORIES.Utility,
    rules: [
        {
            order: 0,
            prefix: [ICON_UTILITY.Expensive],
            leftSignature: LeftSignature.Note,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [notExistedEdid],
            exclude: [],
        },
        {
            order: 1,
            prefix: [ICON_UTILITY.RareThree],
            leftSignature: LeftSignature.Note,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [notExistedEdid],
            exclude: [],
        },
        {
            order: 2,
            prefix: [ICON_UTILITY.RareTwo],
            leftSignature: LeftSignature.Note,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [notExistedEdid],
            exclude: [],
        },
        {
            order: 3,
            prefix: [ICON_UTILITY.RareOne],
            leftSignature: LeftSignature.Note,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [notExistedEdid],
            exclude: [],
        },
        {
            order: 4,
            prefix: [ICON_UTILITY.QOne],
            leftSignature: LeftSignature.Note,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [notExistedEdid],
            exclude: [],
        },
        {
            order: 5,
            prefix: [ICON_UTILITY.QTwo],
            leftSignature: LeftSignature.Note,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [notExistedEdid],
            exclude: [],
        },
        {
            order: 6,
            prefix: [ICON_UTILITY.QThree],
            leftSignature: LeftSignature.Note,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [notExistedEdid],
            exclude: [],
        },
        {
            order: 7,
            prefix: [ICON_UTILITY.QFour],
            leftSignature: LeftSignature.Note,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [notExistedEdid],
            exclude: [],
        },
        {
            order: 8,
            prefix: [ICON_UTILITY.YearTwentySeven],
            leftSignature: LeftSignature.Note,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [notExistedEdid],
            exclude: [],
        },
        {
            order: 9,
            prefix: [ICON_UTILITY.YearTwentySix],
            leftSignature: LeftSignature.Note,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [notExistedEdid],
            exclude: [],
        },
        {
            order: 10,
            prefix: [ICON_UTILITY.YearTwentyFive],
            leftSignature: LeftSignature.Note,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [notExistedEdid],
            exclude: [],
        },
        {
            order: 11,
            prefix: [ICON_UTILITY.YearTwentyFour],
            leftSignature: LeftSignature.Note,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [notExistedEdid],
            exclude: [],
        },
        {
            order: 12,
            prefix: [ICON_UTILITY.YearTwentyThree],
            leftSignature: LeftSignature.Note,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [notExistedEdid],
            exclude: [],
        },
        {
            order: 13,
            prefix: [ICON_UTILITY.YearTwentyTwo],
            leftSignature: LeftSignature.Note,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [notExistedEdid],
            exclude: [],
        },
        {
            order: 14,
            prefix: [ICON_UTILITY.YearTwentyOne],
            leftSignature: LeftSignature.Note,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [notExistedEdid],
            exclude: [],
        },
        {
            order: 15,
            prefix: [ICON_UTILITY.YearTwenty],
            leftSignature: LeftSignature.Note,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [notExistedEdid],
            exclude: [],
        },
        {
            order: 16,
            prefix: [ICON_UTILITY.Empty],
            leftSignature: LeftSignature.Note,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [notExistedEdid],
            exclude: [],
        }
    ],
} as const satisfies RulesGroup<ICON_UTILITY>;
