import { ICON_WEAPONS } from "@/generated/icons-enum";
import { LeftSignature, RightSignature } from "@/constants";
import type { RulesGroup } from "@/types";
import { ICON_CATEGORIES } from "@/generated/icon-categories-enum";
export const WEAPONS_RULES_GROUP = {
    category: ICON_CATEGORIES.Weapons,
    rules: [
        {
            order: 0,
            prefix: [ICON_WEAPONS.Throwing],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|WeaponTypeThrown"],
            exclude: [],
        },
        {
            order: 1,
            prefix: [ICON_WEAPONS.Mine],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|WeaponTypeMine"],
            exclude: [],
        },
        {
            order: 2,
            prefix: [ICON_WEAPONS.HeavyEnergy],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [
                "ekwd|WeaponTypeEnergy",
                "ekwd|WeaponTypeHeavy"
            ],
            exclude: [],
        },
        {
            order: 3,
            prefix: [ICON_WEAPONS.Heavy],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|WeaponTypeHeavy"],
            exclude: [],
        },
        {
            order: 4,
            prefix: [ICON_WEAPONS.RifleEnergy],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [
                "ekwd|WeaponTypeRifle",
                "ekwd|WeaponTypeEnergy"
            ],
            exclude: [],
        },
        {
            order: 5,
            prefix: [ICON_WEAPONS.Rifle],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|WeaponTypeRifle"],
            exclude: [],
        },
        {
            order: 6,
            prefix: [ICON_WEAPONS.PistolEnergy],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [
                "ekwd|WeaponTypeEnergy",
                "ekwd|WeaponTypePistol"
            ],
            exclude: [],
        },
        {
            order: 7,
            prefix: [ICON_WEAPONS.Pistol],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|WeaponTypePistol"],
            exclude: [],
        },
        {
            order: 8,
            prefix: [ICON_WEAPONS.Crossbow],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|WeaponTypeBow"],
            exclude: [],
        },
        {
            order: 9,
            prefix: [ICON_WEAPONS.ShotgunEnergy],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [
                "ekwd|WeaponTypeEnergy",
                "ekwd|WeaponTypeShotgun"
            ],
            exclude: [],
        },
        {
            order: 10,
            prefix: [ICON_WEAPONS.Shotgun],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|WeaponTypeShotgun"],
            exclude: [],
        },
        {
            order: 11,
            prefix: [ICON_WEAPONS.Syringer],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|syringer"],
            exclude: [],
        },
        {
            order: 12,
            prefix: [ICON_WEAPONS.MeleeAuto],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "ekwd|WeaponTypeChainsaw",
                "ekwd|WeaponTypeDrill"
            ],
            exclude: [],
        },
        {
            order: 13,
            prefix: [ICON_WEAPONS.MeleeUnarmed],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|WeaponTypeUnarmed",],
            exclude: [],
        },
        {
            order: 14,
            prefix: [ICON_WEAPONS.MeleeOneHand],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|WeaponTypeMelee1H",],
            exclude: [],
        },
        {
            order: 15,
            prefix: [ICON_WEAPONS.MeleeTwoHand],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|WeaponTypeMelee2H",],
            exclude: [],
        },
        {
            order: 16,
            prefix: [ICON_WEAPONS.Binoculars],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|binoculars"],
            exclude: [],
        },
        {
            order: 17,
            prefix: [ICON_WEAPONS.Camera],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|camera"],
            exclude: [],
        }
    ],
} as const satisfies RulesGroup<ICON_WEAPONS>;
