import { ICON_WEAPONS } from '@/generated/icons-enum';
import { LeftSignature, RightSignature } from '@/constants';
import type { RulesGroup } from '@/types';
import { ICON_CATEGORIES } from '@/generated/icon-categories-enum';

export const WEAPONS_RULES_GROUP = {
  category: ICON_CATEGORIES.Weapons,
  rules: [
    {
      order: 0,
      prefix: [ICON_WEAPONS.UniqueWeapon],
      leftSignature: LeftSignature.InstanceNamingRules,
      rightSignature: RightSignature.WNAM,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x230a',
      include: ['ekwd|CustomItemName'],
      exclude: [],
    },
    {
      order: 1,
      prefix: [ICON_WEAPONS.Binoculars],
      leftSignature: LeftSignature.Weapon,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x230b',
      include: ['edid|binoculars'],
      exclude: [],
    },
    {
      order: 2,
      prefix: [ICON_WEAPONS.Camera],
      leftSignature: LeftSignature.Weapon,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x230c',
      include: ['edid|camera'],
      exclude: [],
    },
    {
      order: 3,
      prefix: [ICON_WEAPONS.AssaultronHead],
      leftSignature: LeftSignature.Weapon,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x230d',
      include: ['edid|AssaultronHead'],
      exclude: [],
    },
    {
      order: 4,
      prefix: [ICON_WEAPONS.Syringer],
      leftSignature: LeftSignature.Weapon,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x230e',
      include: ['edid|syringer'],
      exclude: [],
    },
    {
      order: 5,
      prefix: [ICON_WEAPONS.Bow],
      leftSignature: LeftSignature.Weapon,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x230f',
      include: ['edid|bow'],
      exclude: ['edid|CompoundBow', 'edid|Bowie', 'edid|crossbow'],
    },
    {
      order: 6,
      prefix: [ICON_WEAPONS.CompoundBow],
      leftSignature: LeftSignature.Weapon,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: false,
      isFullReplaced: false,
      header: '0x2310',
      include: ['edid|CompoundBow'],
      exclude: [],
    },
    {
      order: 7,
      prefix: [ICON_WEAPONS.Weapon],
      leftSignature: LeftSignature.Weapon,
      rightSignature: RightSignature.FULL,
      isInjected: false,
      isDeleted: false,
      isAnyKeyword: false,
      isInclusiveOr: true,
      isFullReplaced: false,
      header: '0x2311',
      include: ['edid|10mm', 'edid|crossbow'],
      exclude: [],
    },
  ],
} as const satisfies RulesGroup<ICON_WEAPONS>;
