import { ICON_WEAPONS } from "@/generated/icons-enum";
import { LeftSignature, RightSignature } from "@/constants";
import type { IncludeProperty, RulesGroup } from "@/types";
import { ICON_CATEGORIES } from "@/generated/icon-categories-enum";
const uniqueHeavy = [
    "edid|W05_COMP_Beckett_50CalMachineGun_QuestReward",
    "edid|E08B_Minigun_FoundationsVengeance",
    "edid|Survival_HarpoonGun_Kingfisher",
    "edid|ResoluteVeteran",
    "edid|TheActionHero"
] as const satisfies IncludeProperty[];
const uniqueRifles = [
    "edid|DoctorsOrders",
    "edid|E09C_SubmachineGun_LoveTap",
    "edid|W05_MQS_203P_10mmSMG",
    "edid|SoleSurvivor",
    "edid|WesternSpirit",
    "edid|WhistleInTheDark"
] as const satisfies IncludeProperty[];
const uniqueEnergyRifles = [
    "edid|Survival_LaserGun_AcceptableOverkill",
    "edid|MindOverMatter",
    "edid|NightLight"
] as const satisfies IncludeProperty[];
const uniquePistols = [
    "edid|MTR05_10mm_ScorchedTrainer",
    "edid|MTNL01_SingleActionRevolver_Fancy",
    "edid|E09D_SingleActionRevolver_GunthersRevolver",
    "edid|44_MedicalMalpractice",
    "edid|PiratePunch",
    "edid|VoiceOfSet"
] as const satisfies IncludeProperty[];
const uniqueEnergyPistols = [
    "edid|10mm_CircuitBreaker",
    "edid|ATX_AssaultronHeadCharging_Imposter",
    "edid|PollyAssaultronHead",
    "edid|Astronaut_AlienBlaster",
    "edid|GammaGun_Xerxos"
] as const satisfies IncludeProperty[];
const uniqueShotguns = [
    "edid|ColdShoulder",
    "edid|CrowdControl",
    "edid|MTNL01_PumpActionShotgun_Fancy",
    "edid|SaltOfTheEarth"
] as const satisfies IncludeProperty[];
const uniqueExplosives = [
    "edid|CrushingBlow",
    "edid|GrandFinale",
    "edid|AutoGrenadeLauncher_NukaLauncher",
    "edid|TheGuarantee"
] as const satisfies IncludeProperty[];
const uniqueSyringers = [
    "edid|PipeSyringer_Karma",
    "edid|PipeSyringer_Vox"
] as const satisfies IncludeProperty[];
const explosiveRules = [
    "edid|AutoGrenadeLauncher",
    "edid|Broadsider",
    "edid|Fatman",
    "edid|BOSRocketLauncher",
    "edid|M79",
    "edid|MissileLauncher",
    "edid|ThirstZapper",
    "edid|QuadLauncher"
] as const satisfies IncludeProperty[];
const pepperShakerRule = "edid|PepperShaker" as const;
export const WEAPONS_RULES_GROUP = {
    category: ICON_CATEGORIES.Weapons,
    rules: [
        {
            order: 0,
            prefix: [ICON_WEAPONS.Throwing],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|WeaponTypeThrown"],
            exclude: [],
        },
        {
            order: 1,
            prefix: [ICON_WEAPONS.Throwing],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|CryoGrenade"],
            exclude: [],
        },
        {
            order: 2,
            prefix: [ICON_WEAPONS.Mine],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|WeaponTypeMine"],
            exclude: [],
        },
        {
            order: 3,
            prefix: [ICON_WEAPONS.Unique, ICON_WEAPONS.HeavyEnergy],
            leftSignature: LeftSignature.InstanceNamingRules,
            rightSignature: RightSignature.WNAM,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "ekwd|CustomItemName_BoilingPoint",
                "ekwd|CustomItemName_V63GatlingLaser",
                "ekwd|CustomItemName_Valkyrie",
                "ekwd|CustomItemName_Pyrolyzer",
                "ekwd|CustomItemName_HolyFire",
            ],
            exclude: [],
        },
        {
            order: 4,
            prefix: [ICON_WEAPONS.HeavyEnergy],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [
                "ekwd|WeaponTypeEnergy",
                "ekwd|WeaponTypeHeavy"
            ],
            exclude: [],
        },
        {
            order: 5,
            prefix: [ICON_WEAPONS.Unique, ICON_WEAPONS.Heavy],
            leftSignature: LeftSignature.InstanceNamingRules,
            rightSignature: RightSignature.WNAM,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "ekwd|CustomItemName_FoundationsVengeance",
                "ekwd|CustomItemName_RedTerror",
            ],
            exclude: [],
        },
        {
            order: 6,
            prefix: [ICON_WEAPONS.Unique, ICON_WEAPONS.Heavy],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [...uniqueHeavy],
            exclude: [],
        },
        {
            order: 7,
            prefix: [ICON_WEAPONS.Heavy],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|WeaponTypeHeavy"],
            exclude: [
                ...explosiveRules,
                ...uniqueHeavy,
                pepperShakerRule,
            ],
        },
        {
            order: 8,
            prefix: [ICON_WEAPONS.Unique, ICON_WEAPONS.RifleEnergy],
            leftSignature: LeftSignature.InstanceNamingRules,
            rightSignature: RightSignature.WNAM,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "ekwd|CustomItemName_V63-BERTHA",
                "ekwd|CustomItemName_V63LaserRifle",
                "ekwd|CustomItemName_StrikeBreaker",
                "ekwd|CustomItemName_MindOverMatter",
                "ekwd|CustomItemName_Plasma_W05MQR",
            ],
            exclude: [],
        },
        {
            order: 9,
            prefix: [ICON_WEAPONS.Unique, ICON_WEAPONS.RifleEnergy],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [...uniqueEnergyRifles],
            exclude: [],
        },
        {
            order: 10,
            prefix: [ICON_WEAPONS.RifleEnergy],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [
                "ekwd|WeaponTypeRifle",
                "ekwd|WeaponTypeEnergy"
            ],
            exclude: [...uniqueEnergyRifles],
        },
        {
            order: 11,
            prefix: [ICON_WEAPONS.RifleEnergy],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "edid|UltraciteLaserGun",
                "edid|LaserGun",
                "edid|PlasmaGun",
            ],
            exclude: [...uniqueEnergyRifles],
        },
        {
            order: 12,
            prefix: [ICON_WEAPONS.Unique, ICON_WEAPONS.Rifle],
            leftSignature: LeftSignature.InstanceNamingRules,
            rightSignature: RightSignature.WNAM,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "ekwd|CustomItemName_AnchorageAce",
                "ekwd|CustomItemName_LoveTap",
                "ekwd|CustomItemName_Longshot",
                "ekwd|CustomItemName_WesternSpirit",
                "ekwd|CustomItemName_LicketySplit",
                "ekwd|CustomItemName_TheFixer",
                "ekwd|CustomItemName_EldersMark",
                "ekwd|CustomItemName_TickettoRevenge",
                "ekwd|CustomItemName_ShatteredGrounds",
                "ekwd|CustomItemName_DoctorsOrders",
                "ekwd|CustomItemName_WhistleInTheDark",
                "ekwd|CustomItemName_PerfectStorm",
            ],
            exclude: [],
        },
        {
            order: 13,
            prefix: [ICON_WEAPONS.Unique, ICON_WEAPONS.Rifle],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [...uniqueRifles],
            exclude: [],
        },
        {
            order: 14,
            prefix: [ICON_WEAPONS.Rifle],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|WeaponTypeRifle"],
            exclude: [...uniqueRifles],
        },
        {
            order: 15,
            prefix: [ICON_WEAPONS.Rifle],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|PipeGun"],
            exclude: [...uniqueRifles],
        },
        {
            order: 16,
            prefix: [ICON_WEAPONS.Rifle],
            leftSignature: LeftSignature.InstanceNamingRules,
            rightSignature: RightSignature.WNAM,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|HandmadeAssaultRifle"],
            exclude: [],
        },
        {
            order: 17,
            prefix: [ICON_WEAPONS.Unique, ICON_WEAPONS.PistolEnergy],
            leftSignature: LeftSignature.InstanceNamingRules,
            rightSignature: RightSignature.WNAM,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "ekwd|CustomItemName_CircuitBreaker",
            ],
            exclude: [],
        },
        {
            order: 18,
            prefix: [ICON_WEAPONS.Unique, ICON_WEAPONS.PistolEnergy],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [...uniqueEnergyPistols],
            exclude: [],
        },
        {
            order: 19,
            prefix: [ICON_WEAPONS.PistolEnergy],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [
                "ekwd|WeaponTypeEnergy",
                "ekwd|WeaponTypePistol"
            ],
            exclude: [...uniqueEnergyPistols],
        },
        {
            order: 20,
            prefix: [ICON_WEAPONS.Unique, ICON_WEAPONS.Pistol],
            leftSignature: LeftSignature.InstanceNamingRules,
            rightSignature: RightSignature.WNAM,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "ekwd|CustomItemName_GunthersRevolver",
                "ekwd|CustomItemName_PiratePunch",
                "ekwd|CustomItemName_TheFactFinder",
                "ekwd|CustomItemName_SomersetSpecial"
            ],
            exclude: [],
        },
        {
            order: 21,
            prefix: [ICON_WEAPONS.Unique, ICON_WEAPONS.Pistol],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [...uniquePistols],
            exclude: [],
        },
        {
            order: 22,
            prefix: [ICON_WEAPONS.Pistol],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|WeaponTypePistol"],
            exclude: [...uniquePistols],
        },
        {
            order: 23,
            prefix: [ICON_WEAPONS.Unique, ICON_WEAPONS.Crossbow],
            leftSignature: LeftSignature.InstanceNamingRules,
            rightSignature: RightSignature.WNAM,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "ekwd|CustomItemName_BurningLove",
            ],
            exclude: [],
        },
        {
            order: 24,
            prefix: [ICON_WEAPONS.Crossbow],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|WeaponTypeBow"],
            exclude: [],
        },
        {
            order: 25,
            prefix: [ICON_WEAPONS.ShotgunEnergy],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: [
                "ekwd|WeaponTypeEnergy",
                "ekwd|WeaponTypeShotgun"
            ],
            exclude: [],
        },
        {
            order: 26,
            prefix: [ICON_WEAPONS.Unique, ICON_WEAPONS.Shotgun],
            leftSignature: LeftSignature.InstanceNamingRules,
            rightSignature: RightSignature.WNAM,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "ekwd|CustomItemName_CivilUnrest",
                "ekwd|CustomItemName_TheKabloom",
                "ekwd|CustomItemName_CrowdControl"
            ],
        },
        {
            order: 27,
            prefix: [ICON_WEAPONS.Unique, ICON_WEAPONS.Shotgun],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [...uniqueShotguns],
        },
        {
            order: 28,
            prefix: [ICON_WEAPONS.Shotgun],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|WeaponTypeShotgun"],
            exclude: [...uniqueShotguns],
        },
        {
            order: 29,
            prefix: [ICON_WEAPONS.Shotgun],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [pepperShakerRule],
            exclude: [...uniqueShotguns],
        },
        {
            order: 30,
            prefix: [ICON_WEAPONS.Unique, ICON_WEAPONS.Explosive],
            leftSignature: LeftSignature.InstanceNamingRules,
            rightSignature: RightSignature.WNAM,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "ekwd|CustomItemName_Boomstick",
                "ekwd|CustomItemName_BunkerBuster",
                "ekwd|CustomItemName_Daisycutter",
                "ekwd|CustomItemName_GrandFinale",
                "ekwd|CustomItemName_NukaLauncher",
                "ekwd|CustomItemName_Overkill",
                "ekwd|CustomItemName_ResolveBreaker",
                "ekwd|CustomItemName_ThePeacemaker",
            ],
            exclude: [],
        },
        {
            order: 31,
            prefix: [ICON_WEAPONS.Unique, ICON_WEAPONS.Explosive],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [...uniqueExplosives],
            exclude: [],
        },
        {
            order: 32,
            prefix: [ICON_WEAPONS.Explosive],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [...explosiveRules],
            exclude: [...uniqueExplosives],
        },
        {
            order: 33,
            prefix: [ICON_WEAPONS.Unique, ICON_WEAPONS.Syringer],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [...uniqueSyringers],
            exclude: [],
        },
        {
            order: 34,
            prefix: [ICON_WEAPONS.Syringer],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|syringer"],
            exclude: [...uniqueSyringers],
        },
        {
            order: 35,
            prefix: [ICON_WEAPONS.Unique, ICON_WEAPONS.MeleeAuto],
            leftSignature: LeftSignature.InstanceNamingRules,
            rightSignature: RightSignature.WNAM,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "ekwd|CustomItemName_Cauterizer"
            ],
        },
        {
            order: 36,
            prefix: [ICON_WEAPONS.MeleeAuto],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "ekwd|WeaponTypeChainsaw",
                "ekwd|WeaponTypeDrill"
            ],
            exclude: [],
        },
        {
            order: 37,
            prefix: [ICON_WEAPONS.Unique, ICON_WEAPONS.MeleeUnarmed],
            leftSignature: LeftSignature.InstanceNamingRules,
            rightSignature: RightSignature.WNAM,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "ekwd|CustomItemName_DrillFist",
                "ekwd|CustomItemName_OguaGauntlet",
                "ekwd|CustomItemName_ToneDeath"
            ],
            exclude: [],
        },
        {
            order: 38,
            prefix: [ICON_WEAPONS.MeleeUnarmed],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|WeaponTypeUnarmed",],
            exclude: [],
        },
        {
            order: 39,
            prefix: [ICON_WEAPONS.Unique, ICON_WEAPONS.MeleeOneHand],
            leftSignature: LeftSignature.InstanceNamingRules,
            rightSignature: RightSignature.WNAM,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "ekwd|CustomItemName_LucaSwitchblade",
                "ekwd|CustomItemName_BlueRidgeBrandingIron",
                "ekwd|CustomItemName_CryptidJawboneKnife",
                "ekwd|CustomItemName_V63ShockBaton",
                "ekwd|CustomItemName_TheGutter",
                "ekwd|CustomItemName_BlackDiamond"
            ],
            exclude: [],
        },
        {
            order: 40,
            prefix: [ICON_WEAPONS.MeleeOneHand],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|WeaponTypeMelee1H",],
            exclude: [],
        },
        {
            order: 41,
            prefix: [ICON_WEAPONS.Unique, ICON_WEAPONS.MeleeTwoHand],
            leftSignature: LeftSignature.InstanceNamingRules,
            rightSignature: RightSignature.WNAM,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: true,
            isFullReplaced: false,
            include: [
                "ekwd|CustomItemName_TheDebilitator",
                "ekwd|CustomItemName_WhackerSmacker",
                "ekwd|CustomItemName_RatBat",
                "ekwd|CustomItemName_AllRise",
                // bug
                "ekwd|CustomItemName_HeadHunter",
                "ekwd|CustomItemName_UltraciteTerrorSword",
                "ekwd|CustomItemName_CultistPiercer",
                "ekwd|CustomItemName_TheFarmhand",
                "ekwd|CustomItemName_StrongmansSledgehammer"
            ],
            exclude: [],
        },
        {
            order: 42,
            prefix: [ICON_WEAPONS.MeleeTwoHand],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["ekwd|WeaponTypeMelee2H",],
            exclude: [],
        },
        {
            order: 43,
            prefix: [ICON_WEAPONS.Binoculars],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|binoculars"],
            exclude: [],
        },
        {
            order: 44,
            prefix: [ICON_WEAPONS.Camera],
            leftSignature: LeftSignature.Weapon,
            rightSignature: RightSignature.FULL,
            isInjected: false,
            isDeleted: false,
            isAnyKeyword: false,
            isInclusiveOr: false,
            isFullReplaced: false,
            include: ["edid|camera"],
            exclude: [],
        }
    ],
} as const satisfies RulesGroup<ICON_WEAPONS>;
