import { ICON_APPAREL } from '@/generated/icons-enum';
import { LeftSignature, RightSignature } from '@/constants';
import type { Rule } from '@/types';

export const APPAREL_RULES: Rule<ICON_APPAREL>[] = [
  {
    order: 0,
    iconName: ICON_APPAREL.Helmet,
    leftSignature: LeftSignature.Armor,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: true,
    isFullReplaced: false,
    header: '0x22f4',
    include: ['ekwd|ClothingTypeHat', 'ekwd|ArmorBodyPartHead'],
    exclude: [
      'ekwd|ClothingTypeGasMask',
      'ekwd|ClothingTypeFedora',
      'ekwd|HatTypeFasnachtMask',
      'ekwd|ClothingTypeGlasses',
    ],
  },
  {
    order: 1,
    iconName: ICON_APPAREL.FedoraHat,
    leftSignature: LeftSignature.Armor,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x22f5',
    include: ['ekwd|ClothingTypeHat', 'ekwd|ClothingTypeFedora'],
    exclude: [],
  },
  {
    order: 2,
    iconName: ICON_APPAREL.FasnachtMask,
    leftSignature: LeftSignature.Armor,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x22f6',
    include: ['ekwd|ClothingTypeHat', 'ekwd|HatTypeFasnachtMask'],
    exclude: [],
  },
  {
    order: 3,
    iconName: ICON_APPAREL.Beret,
    leftSignature: LeftSignature.Armor,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x22f7',
    include: ['edid|beret'],
    exclude: [],
  },
  {
    order: 4,
    iconName: ICON_APPAREL.GasMask,
    leftSignature: LeftSignature.Armor,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x22f8',
    include: ['ekwd|ClothingTypeMask', 'ekwd|ClothingTypeGasMask'],
    exclude: [],
  },
  {
    order: 5,
    iconName: ICON_APPAREL.Glasses,
    leftSignature: LeftSignature.Armor,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x22f9',
    include: ['ekwd|ClothingTypeGlasses'],
    exclude: [],
  },
  {
    order: 6,
    iconName: ICON_APPAREL.Dress,
    leftSignature: LeftSignature.Armor,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x22fa',
    include: ['ekwd|ClothingTypeDress'],
    exclude: [],
  },
  {
    order: 7,
    iconName: ICON_APPAREL.Suit,
    leftSignature: LeftSignature.Armor,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x22fb',
    include: ['ekwd|ClothingTypeFormalWear'],
    exclude: ['ekwd|ClothingTypeDress'],
  },
  {
    order: 8,
    iconName: ICON_APPAREL.Apparel,
    leftSignature: LeftSignature.Armor,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x22fc',
    include: ['ekwd|ObjectTypeClothing'],
    exclude: [
      'ekwd|ClothingTypeHat',
      'ekwd|ClothingTypeGasMask',
      'ekwd|ClothingTypeDress',
      'ekwd|ClothingTypeFormalWear',
    ],
  },
];
