import { ICON_ARMOR } from '@/generated/icons-enum';
import { LeftSignature, RightSignature } from '@/constants';
import type { Rule } from '@/types';

export const ARMOR_RULES: Rule<ICON_ARMOR>[] = [
  {
    order: 0,
    iconName: ICON_ARMOR.TFortyFive,
    leftSignature: LeftSignature.InstanceNamingRules,
    rightSignature: RightSignature.WNAM,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: true,
    header: '0x22fd',
    include: ['ekwd|t45'],
    exclude: [],
  },
  {
    order: 1,
    iconName: ICON_ARMOR.TFivtyOne,
    leftSignature: LeftSignature.InstanceNamingRules,
    rightSignature: RightSignature.WNAM,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: true,
    header: '0x22fe',
    include: ['ekwd|t51'],
    exclude: [],
  },
  {
    order: 2,
    iconName: ICON_ARMOR.TSixty,
    leftSignature: LeftSignature.InstanceNamingRules,
    rightSignature: RightSignature.WNAM,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: true,
    header: '0x22ff',
    include: ['ekwd|t60'],
    exclude: [],
  },
  {
    order: 3,
    iconName: ICON_ARMOR.TSixtyFive,
    leftSignature: LeftSignature.InstanceNamingRules,
    rightSignature: RightSignature.WNAM,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: true,
    header: '0x2300',
    include: ['ekwd|PowerArmor_T65'],
    exclude: [],
  },
  {
    order: 4,
    iconName: ICON_ARMOR.XOne,
    leftSignature: LeftSignature.InstanceNamingRules,
    rightSignature: RightSignature.WNAM,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: true,
    header: '0x2301',
    include: ['ekwd|x01'],
    exclude: [],
  },
  {
    order: 5,
    iconName: ICON_ARMOR.PowerArmorHelmet,
    leftSignature: LeftSignature.InstanceNamingRules,
    rightSignature: RightSignature.WNAM,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x2302',
    include: ['ekwd|PowerArmor'],
    exclude: [
      'ekwd|PowerArmor_Helmet',
      'ekwd|PowerArmor_LeftArm',
      'ekwd|PowerArmor_RightArm',
      'ekwd|PowerArmor_LeftLeg',
      'ekwd|PowerArmor_RightLeg',
      'ekwd|PowerArmor_Torso',
      'ekwd|t45',
      'ekwd|t51',
      'ekwd|t60',
      'ekwd|PowerArmor_T65',
      'ekwd|x01',
    ],
  },
  {
    order: 6,
    iconName: ICON_ARMOR.Underarmor,
    leftSignature: LeftSignature.Armor,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x2303',
    include: ['ekwd|ObjectTypeUnderarmor'],
    exclude: [],
  },
  {
    order: 7,
    iconName: ICON_ARMOR.Spacesuit,
    leftSignature: LeftSignature.Armor,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x2304',
    include: ['ekwd|ClothingTypeSpacesuit'],
    exclude: [],
  },
  {
    order: 8,
    iconName: ICON_ARMOR.ChestArmor,
    leftSignature: LeftSignature.Armor,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x2305',
    include: ['ekwd|ObjectTypeArmor'],
    exclude: [
      'ekwd|ClothingTypeSpacesuit',
      'ekwd|ArmorBodyPartHands',
      'ekwd|ArmorBodyPartFeet',
    ],
  },
  {
    order: 9,
    iconName: ICON_ARMOR.ArmorRightArm,
    leftSignature: LeftSignature.Armor,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x2306',
    include: [
      'ekwd|ObjectTypeArmor',
      'ekwd|ArmorBodyPartHands',
      'ekwd|ArmRight',
    ],
    exclude: ['ekwd|ArmorTypePower'],
  },
  {
    order: 10,
    iconName: ICON_ARMOR.ArmorLeftArm,
    leftSignature: LeftSignature.Armor,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x2307',
    include: [
      'ekwd|ObjectTypeArmor',
      'ekwd|ArmorBodyPartHands',
      'ekwd|ArmLeft',
    ],
    exclude: ['ekwd|ArmorTypePower'],
  },
  {
    order: 11,
    iconName: ICON_ARMOR.ArmorRightLeg,
    leftSignature: LeftSignature.Armor,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x2308',
    include: [
      'ekwd|ObjectTypeArmor',
      'ekwd|ArmorBodyPartFeet',
      'ekwd|LegRight',
    ],
    exclude: ['ekwd|ArmorTypePower'],
  },
  {
    order: 12,
    iconName: ICON_ARMOR.ArmorLeftLeg,
    leftSignature: LeftSignature.Armor,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x2309',
    include: ['ekwd|ObjectTypeArmor', 'ekwd|ArmorBodyPartFeet', 'ekwd|LegLeft'],
    exclude: ['ekwd|ArmorTypePower'],
  },
];
