import { ICON_HEAVY_WEAPONS } from '@/generated/icons-enum';
import { LeftSignature, RightSignature } from '@/constants';
import type { Rule } from '@/types';

export const HEAVY_WEAPONS_RULES: Rule[] = [
  {
    order: 0,
    iconName: ICON_HEAVY_WEAPONS.Flamer,
    leftSignature: LeftSignature.Weapon,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x2321',
    include: ['ekwd|WeaponTypeFlamer'],
    exclude: [],
  },
  {
    order: 1,
    iconName: ICON_HEAVY_WEAPONS.Cryolator,
    leftSignature: LeftSignature.Weapon,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x2322',
    include: ['ekwd|WeaponTypeCryolator'],
    exclude: [],
  },
  {
    order: 2,
    iconName: ICON_HEAVY_WEAPONS.MachineGun,
    leftSignature: LeftSignature.Weapon,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x2323',
    include: ['ekwd|50calMachineGun'],
    exclude: [],
  },
  {
    order: 3,
    iconName: ICON_HEAVY_WEAPONS.LightMachineGun,
    leftSignature: LeftSignature.Weapon,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x2324',
    include: ['ekwd|mg42'],
    exclude: [],
  },
  {
    order: 4,
    iconName: ICON_HEAVY_WEAPONS.GatlingLaser,
    leftSignature: LeftSignature.Weapon,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x2325',
    include: ['ekwd|GatlingLaser'],
    exclude: [],
  },
  {
    order: 5,
    iconName: ICON_HEAVY_WEAPONS.GatlingPlasma,
    leftSignature: LeftSignature.Weapon,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x2326',
    include: ['edid|GatlingPlasma'],
    exclude: ['ekwd|GatlingLaser'],
  },
  {
    order: 6,
    iconName: ICON_HEAVY_WEAPONS.GatlingGun,
    leftSignature: LeftSignature.Weapon,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x2327',
    include: ['edid|GatlingGun'],
    exclude: [],
  },
  {
    order: 7,
    iconName: ICON_HEAVY_WEAPONS.PlasmaCaster,
    leftSignature: LeftSignature.Weapon,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x2328',
    include: ['edid|PlasmaCaster'],
    exclude: [],
  },
  {
    order: 8,
    iconName: ICON_HEAVY_WEAPONS.Minigun,
    leftSignature: LeftSignature.Weapon,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x2329',
    include: ['edid|minigun'],
    exclude: [],
  },
  {
    order: 9,
    iconName: ICON_HEAVY_WEAPONS.Broadsider,
    leftSignature: LeftSignature.Weapon,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x232a',
    include: ['edid|broadsider'],
    exclude: [],
  },
  {
    order: 10,
    iconName: ICON_HEAVY_WEAPONS.MissileLauncher,
    leftSignature: LeftSignature.Weapon,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x232b',
    include: ['edid|MissileLauncher'],
    exclude: [],
  },
  {
    order: 11,
    iconName: ICON_HEAVY_WEAPONS.HellstormMissileLauncher,
    leftSignature: LeftSignature.Weapon,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x232c',
    include: ['edid|BOSRocketLauncher'],
    exclude: [],
  },
  {
    order: 12,
    iconName: ICON_HEAVY_WEAPONS.GrenadeLauncher,
    leftSignature: LeftSignature.Weapon,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x232d',
    include: ['edid|m79'],
    exclude: [],
  },
  {
    order: 13,
    iconName: ICON_HEAVY_WEAPONS.AutoGrenadeLauncher,
    leftSignature: LeftSignature.Weapon,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x232e',
    include: ['edid|GrenadeLauncher'],
    exclude: ['ekwd|m79'],
  },
  {
    order: 14,
    iconName: ICON_HEAVY_WEAPONS.Fatman,
    leftSignature: LeftSignature.Weapon,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x232f',
    include: ['edid|fatman'],
    exclude: [],
  },
  {
    order: 15,
    iconName: ICON_HEAVY_WEAPONS.HarpoonGun,
    leftSignature: LeftSignature.Weapon,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x2330',
    include: ['edid|HarpoonGun'],
    exclude: [],
  },
  {
    order: 16,
    iconName: ICON_HEAVY_WEAPONS.JunkJet,
    leftSignature: LeftSignature.Weapon,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x2331',
    include: ['edid|JunkJet'],
    exclude: [],
  },
];
