import { ICON_KEYS } from '@/generated/icons-enum';
import { LeftSignature, RightSignature } from '@/constants';
import type { Rule } from '@/types';

export const KEYS_RULES: Rule[] = [
  {
    order: 0,
    iconName: ICON_KEYS.AccessCard,
    leftSignature: LeftSignature.Key,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: true,
    isFullReplaced: false,
    header: '0x22ac',
    include: [
      'edid|keycard',
      'edid|password',
      'edid|code',
      'edid|card',
      'edid|login',
      'edid|terminal',
      'edid|organics',
      'edid|databank',
      'edid|RecallKey',
      'edid|TheMazeID',
      'edid|CongressionalID',
      'edid|BiometricData',
      'edid|RDClearance',
      'edid|TaggerdyID',
      'edid|SeniorExecID',
    ],
    exclude: [],
  },
  {
    order: 1,
    iconName: ICON_KEYS.Key,
    leftSignature: LeftSignature.Key,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x22ad',
    include: ['edid|key'],
    exclude: [
      'edid|keycard',
      'edid|password',
      'edid|code',
      'edid|card',
      'edid|login',
      'edid|terminal',
      'edid|organics',
      'edid|databank',
      'edid|RecallKey',
      'edid|TheMazeID',
      'edid|CongressionalID',
      'edid|BiometricData',
      'edid|RDClearance',
      'edid|TaggerdyID',
      'edid|SeniorExecID',
    ],
  },
];
