import { ICON_LEGENDARY_EFFECTS } from '../generated/icons-enum';
import { LeftSignature, RightSignature } from '../utils/const';
import type { Rule } from '../utils/types';

export const LEGENDARY_EFFECTS_RULES: Rule[] = [
  {
    order: 0,
    iconName: ICON_LEGENDARY_EFFECTS.Unyielding,
    leftSignature: LeftSignature.InstanceNamingRules,
    rightSignature: RightSignature.WNAM,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: true,
    isFullReplaced: true,
    header: '0x2275',
    include: [
      'ekwd|HasLegendary_Weapon_Steady',
      'ekwd|HasLegendary_Armor_LowHealthIncreasesStats',
    ],
    exclude: [],
  },
  {
    order: 1,
    iconName: ICON_LEGENDARY_EFFECTS.AntiArmor,
    leftSignature: LeftSignature.InstanceNamingRules,
    rightSignature: RightSignature.WNAM,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: true,
    header: '0x2276',
    include: ['ekwd|HasLegendary_Weapon_AntiArmor'],
    exclude: [],
  },
  {
    order: 2,
    iconName: ICON_LEGENDARY_EFFECTS.Bloodied,
    leftSignature: LeftSignature.InstanceNamingRules,
    rightSignature: RightSignature.WNAM,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: true,
    header: '0x2277',
    include: ['ekwd|HasLegendary_Weapon_DamageInverseHealth'],
    exclude: [],
  },
  {
    order: 3,
    iconName: ICON_LEGENDARY_EFFECTS.Junkie,
    leftSignature: LeftSignature.InstanceNamingRules,
    rightSignature: RightSignature.WNAM,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: true,
    header: '0x2278',
    include: ['ekwd|HasLegendary_Weapon_DamageAddiction'],
    exclude: [],
  },
  {
    order: 4,
    iconName: ICON_LEGENDARY_EFFECTS.Gourmand,
    leftSignature: LeftSignature.InstanceNamingRules,
    rightSignature: RightSignature.WNAM,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: true,
    isFullReplaced: true,
    header: '0x2279',
    include: [
      'ekwd|HasLegendary_Weapon_Gourmand',
      'ekwd|HasLegendary_Armor_Overeater',
    ],
    exclude: [],
  },
  {
    order: 5,
    iconName: ICON_LEGENDARY_EFFECTS.Aristocrat,
    leftSignature: LeftSignature.InstanceNamingRules,
    rightSignature: RightSignature.WNAM,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: true,
    isFullReplaced: true,
    header: '0x227a',
    include: [
      'ekwd|HasLegendary_Armor_ResistancesProportionalCaps',
      'ekwd|HasLegendary_Weapon_DamageViaCaps',
    ],
    exclude: [],
  },
  {
    order: 6,
    iconName: ICON_LEGENDARY_EFFECTS.Instigating,
    leftSignature: LeftSignature.InstanceNamingRules,
    rightSignature: RightSignature.WNAM,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: true,
    header: '0x227b',
    include: ['ekwd|HasLegendary_Weapon_DamageFirstBlood'],
    exclude: [],
  },
  {
    order: 7,
    iconName: ICON_LEGENDARY_EFFECTS.Jaggernaut,
    leftSignature: LeftSignature.InstanceNamingRules,
    rightSignature: RightSignature.WNAM,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: true,
    header: '0x227c',
    include: ['ekwd|HasLegendary_Weapon_DamageViaHealth'],
    exclude: [],
  },
  {
    order: 8,
    iconName: ICON_LEGENDARY_EFFECTS.Mutant,
    leftSignature: LeftSignature.InstanceNamingRules,
    rightSignature: RightSignature.WNAM,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: true,
    isFullReplaced: true,
    header: '0x227d',
    include: [
      'ekwd|HasLegendary_Armor_ResistancesMutation',
      'ekwd|HasLegendary_Weapon_DamageWithMutation',
    ],
    exclude: [],
  },
  {
    order: 9,
    iconName: ICON_LEGENDARY_EFFECTS.Berserker,
    leftSignature: LeftSignature.InstanceNamingRules,
    rightSignature: RightSignature.WNAM,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: true,
    header: '0x227e',
    include: ['ekwd|HasLegendary_Weapon_DamageUnarmored'],
    exclude: [],
  },
  {
    order: 10,
    iconName: ICON_LEGENDARY_EFFECTS.Quad,
    leftSignature: LeftSignature.InstanceNamingRules,
    rightSignature: RightSignature.WNAM,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: true,
    header: '0x227f',
    include: ['ekwd|HasLegendary_Weapon_AmmoCapacity4x'],
    exclude: [],
  },
  {
    order: 11,
    iconName: ICON_LEGENDARY_EFFECTS.TwoShot,
    leftSignature: LeftSignature.InstanceNamingRules,
    rightSignature: RightSignature.WNAM,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: true,
    header: '0x2280',
    include: ['ekwd|HasLegendary_Weapon_TwoShot'],
    exclude: [],
  },
  {
    order: 12,
    iconName: ICON_LEGENDARY_EFFECTS.Zealot,
    leftSignature: LeftSignature.InstanceNamingRules,
    rightSignature: RightSignature.WNAM,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: true,
    isFullReplaced: true,
    header: '0x2281',
    include: [
      'ekwd|HasLegendary_Armor_LessDMGScorched',
      'ekwd|HasLegendary_Weapon_DamageVsScorched',
    ],
    exclude: [],
  },
  {
    order: 13,
    iconName: ICON_LEGENDARY_EFFECTS.Nocturnal,
    leftSignature: LeftSignature.InstanceNamingRules,
    rightSignature: RightSignature.WNAM,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: true,
    isFullReplaced: true,
    header: '0x2282',
    include: [
      'ekwd|HasLegendary_Armor_ResistancesNight',
      'ekwd|HasLegendary_Weapon_DamageNight',
    ],
    exclude: [],
  },
  {
    order: 14,
    iconName: ICON_LEGENDARY_EFFECTS.Exterminator,
    leftSignature: LeftSignature.InstanceNamingRules,
    rightSignature: RightSignature.WNAM,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: true,
    isFullReplaced: true,
    header: '0x2283',
    include: [
      'ekwd|HasLegendary_Armor_LessDMGBugs',
      'ekwd|HasLegendary_Weapon_DamageVsBugs',
    ],
    exclude: [],
  },
  {
    order: 15,
    iconName: ICON_LEGENDARY_EFFECTS.Assassin,
    leftSignature: LeftSignature.InstanceNamingRules,
    rightSignature: RightSignature.WNAM,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: true,
    isFullReplaced: true,
    header: '0x2284',
    include: [
      'ekwd|HasLegendary_Armor_LessDMGHumans',
      'ekwd|HasLegendary_Weapon_DamageVsPlayers',
    ],
    exclude: [],
  },
  {
    order: 16,
    iconName: ICON_LEGENDARY_EFFECTS.Furious,
    leftSignature: LeftSignature.InstanceNamingRules,
    rightSignature: RightSignature.WNAM,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: true,
    header: '0x2285',
    include: ['ekwd|HasLegendary_Weapon_DamageConsecutiveHits'],
    exclude: [],
  },
  {
    order: 17,
    iconName: ICON_LEGENDARY_EFFECTS.Troubleshooter,
    leftSignature: LeftSignature.InstanceNamingRules,
    rightSignature: RightSignature.WNAM,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: true,
    isFullReplaced: true,
    header: '0x2286',
    include: [
      'ekwd|HasLegendary_Weapon_DamageVsRobots',
      'ekwd|HasLegendary_Armor_LessDMGRobots',
    ],
    exclude: [],
  },
  {
    order: 18,
    iconName: ICON_LEGENDARY_EFFECTS.MutantSlayer,
    leftSignature: LeftSignature.InstanceNamingRules,
    rightSignature: RightSignature.WNAM,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: true,
    isFullReplaced: true,
    header: '0x2287',
    include: [
      'ekwd|HasLegendary_Armor_LessDMGSupermutants',
      'ekwd|HasLegendary_Weapon_DamageVsSupermutants',
    ],
    exclude: [],
  },
  {
    order: 19,
    iconName: ICON_LEGENDARY_EFFECTS.Executioner,
    leftSignature: LeftSignature.InstanceNamingRules,
    rightSignature: RightSignature.WNAM,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: true,
    header: '0x2288',
    include: ['ekwd|HasLegendary_Weapon_Execute'],
    exclude: [],
  },
  {
    order: 20,
    iconName: ICON_LEGENDARY_EFFECTS.Hunter,
    leftSignature: LeftSignature.InstanceNamingRules,
    rightSignature: RightSignature.WNAM,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: true,
    isFullReplaced: true,
    header: '0x2289',
    include: [
      'ekwd|HasLegendary_Weapon_DamageVsAnimals',
      'ekwd|HasLegendary_Armor_LessDMGAnimals',
    ],
    exclude: [],
  },
  {
    order: 21,
    iconName: ICON_LEGENDARY_EFFECTS.Bolstering,
    leftSignature: LeftSignature.InstanceNamingRules,
    rightSignature: RightSignature.WNAM,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: true,
    header: '0x228a',
    include: ['ekwd|HasLegendary_Armor_ResistancesInverseHealth'],
    exclude: [],
  },
  {
    order: 22,
    iconName: ICON_LEGENDARY_EFFECTS.Stalker,
    leftSignature: LeftSignature.InstanceNamingRules,
    rightSignature: RightSignature.WNAM,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: true,
    header: '0x228b',
    include: ['ekwd|HasLegendary_Weapon_AccuracyNotInCombat'],
    exclude: [],
  },
  {
    order: 23,
    iconName: ICON_LEGENDARY_EFFECTS.Chameleon,
    leftSignature: LeftSignature.InstanceNamingRules,
    rightSignature: RightSignature.WNAM,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: true,
    header: '0x228c',
    include: ['ekwd|HasLegendary_Armor_Chameleon'],
    exclude: [],
  },
  {
    order: 24,
    iconName: ICON_LEGENDARY_EFFECTS.GhoulSlayer,
    leftSignature: LeftSignature.InstanceNamingRules,
    rightSignature: RightSignature.WNAM,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: true,
    isFullReplaced: true,
    header: '0x228d',
    include: [
      'ekwd|HasLegendary_Weapon_DamageVsGhouls',
      'ekwd|HasLegendary_Armor_LessDMGGhouls',
    ],
    exclude: [],
  },
  {
    order: 25,
    iconName: ICON_LEGENDARY_EFFECTS.LifeSaving,
    leftSignature: LeftSignature.InstanceNamingRules,
    rightSignature: RightSignature.WNAM,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: true,
    header: '0x228e',
    include: ['ekwd|HasLegendary_Armor_AutoRevive'],
    exclude: [],
  },
  {
    order: 26,
    iconName: ICON_LEGENDARY_EFFECTS.Vanguard,
    leftSignature: LeftSignature.InstanceNamingRules,
    rightSignature: RightSignature.WNAM,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: true,
    header: '0x228f',
    include: ['ekwd|HasLegendary_Armor_ResistancesProportionalHealth'],
    exclude: [],
  },
  {
    order: 27,
    iconName: ICON_LEGENDARY_EFFECTS.Cloaking,
    leftSignature: LeftSignature.InstanceNamingRules,
    rightSignature: RightSignature.WNAM,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: true,
    header: '0x2290',
    include: ['ekwd|HasLegendary_Armor_GettingMeleedTriggersInvisibility'],
    exclude: [],
  },
  {
    order: 28,
    iconName: ICON_LEGENDARY_EFFECTS.Supressor,
    leftSignature: LeftSignature.InstanceNamingRules,
    rightSignature: RightSignature.WNAM,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: true,
    header: '0x2291',
    include: ['ekwd|HasLegendary_Weapon_DebuffDamage'],
    exclude: [],
  },
  {
    order: 29,
    iconName: ICON_LEGENDARY_EFFECTS.Vampire,
    leftSignature: LeftSignature.InstanceNamingRules,
    rightSignature: RightSignature.WNAM,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: true,
    header: '0x2292',
    include: ['ekwd|HasLegendary_Weapon_Vampire'],
    exclude: [],
  },
  {
    order: 30,
    iconName: ICON_LEGENDARY_EFFECTS.Medic,
    leftSignature: LeftSignature.InstanceNamingRules,
    rightSignature: RightSignature.WNAM,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: true,
    isFullReplaced: true,
    header: '0x2293',
    include: [
      'ekwd|HasLegendary_Weapon_CitsHealGroup',
      'ekwd|dn_BackPack_Standard_Material_Medical',
      'ekwd|dn_HasMisc_MedicPump',
    ],
    exclude: [],
  },
  {
    order: 31,
    iconName: ICON_LEGENDARY_EFFECTS.AutoStim,
    leftSignature: LeftSignature.InstanceNamingRules,
    rightSignature: RightSignature.WNAM,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: true,
    header: '0x2294',
    include: ['ekwd|HasLegendary_Armor_LowHealthTriggersStimpak'],
    exclude: [],
  },
  {
    order: 32,
    iconName: ICON_LEGENDARY_EFFECTS.Regenerating,
    leftSignature: LeftSignature.InstanceNamingRules,
    rightSignature: RightSignature.WNAM,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: true,
    header: '0x2295',
    include: ['ekwd|HasLegendary_Armor_HealthRegen'],
    exclude: [],
  },
  {
    order: 33,
    iconName: ICON_LEGENDARY_EFFECTS.Weightless,
    leftSignature: LeftSignature.InstanceNamingRules,
    rightSignature: RightSignature.WNAM,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: true,
    header: '0x2296',
    include: ['ekwd|HasLegendary_Armor_Weightless'],
    exclude: [],
  },
  {
    order: 34,
    iconName: '_injected_innr_eraser',
    leftSignature: LeftSignature.InstanceNamingRules,
    rightSignature: RightSignature.WNAM,
    isInjected: true,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: true,
    header: ' 0x020',
    include: [],
    exclude: [
      'ekwd|CustomItemName',
      'ekwd|PowerArmor',
      'ekwd|HandmadeRifle',
      'ekwd|PipeWrench_Flowers',
      'ekwd|HasLegendary_Weapon_Steady',
      'ekwd|HasLegendary_Armor_LowHealthIncreasesStats',
      'ekwd|HasLegendary_Weapon_AntiArmor',
      'ekwd|HasLegendary_Weapon_DamageInverseHealth',
      'ekwd|HasLegendary_Weapon_DamageAddiction',
      'ekwd|HasLegendary_Weapon_Gourmand',
      'ekwd|HasLegendary_Armor_Overeater',
      'ekwd|HasLegendary_Armor_ResistancesProportionalCaps',
      'ekwd|HasLegendary_Weapon_DamageViaCaps',
      'ekwd|HasLegendary_Weapon_DamageFirstBlood',
      'ekwd|HasLegendary_Weapon_DamageViaHealth',
      'ekwd|HasLegendary_Armor_ResistancesMutation',
      'ekwd|HasLegendary_Weapon_DamageWithMutation',
      'ekwd|HasLegendary_Weapon_DamageUnarmored',
      'ekwd|HasLegendary_Weapon_AmmoCapacity4x',
      'ekwd|HasLegendary_Weapon_TwoShot',
      'ekwd|HasLegendary_Armor_LessDMGScorched',
      'ekwd|HasLegendary_Weapon_DamageVsScorched',
      'ekwd|HasLegendary_Armor_ResistancesNight',
      'ekwd|HasLegendary_Weapon_DamageNight',
      'ekwd|HasLegendary_Armor_LessDMGBugs',
      'ekwd|HasLegendary_Weapon_DamageVsBugs',
      'ekwd|HasLegendary_Armor_LessDMGHumans',
      'ekwd|HasLegendary_Weapon_DamageVsPlayers',
      'ekwd|HasLegendary_Weapon_DamageConsecutiveHits',
      'ekwd|HasLegendary_Weapon_DamageVsRobots',
      'ekwd|HasLegendary_Armor_LessDMGRobots',
      'ekwd|HasLegendary_Armor_LessDMGSupermutants',
      'ekwd|HasLegendary_Weapon_DamageVsSupermutants',
      'ekwd|HasLegendary_Weapon_Execute',
      'ekwd|HasLegendary_Weapon_DamageVsAnimals',
      'ekwd|HasLegendary_Armor_LessDMGAnimals',
      'ekwd|HasLegendary_Armor_ResistancesInverseHealth',
      'ekwd|HasLegendary_Weapon_AccuracyNotInCombat',
      'ekwd|HasLegendary_Armor_Chameleon',
      'ekwd|HasLegendary_Weapon_DamageVsGhouls',
      'ekwd|HasLegendary_Armor_LessDMGGhouls',
      'ekwd|HasLegendary_Armor_AutoRevive',
      'ekwd|HasLegendary_Armor_ResistancesProportionalHealth',
      'ekwd|HasLegendary_Armor_GettingMeleedTriggersInvisibility',
      'ekwd|HasLegendary_Weapon_DebuffDamage',
      'ekwd|HasLegendary_Weapon_Vampire',
      'ekwd|HasLegendary_Weapon_CitsHealGroup',
      'ekwd|dn_BackPack_Standard_Material_Medical',
      'ekwd|dn_HasMisc_MedicPump',
      'ekwd|HasLegendary_Armor_LowHealthTriggersStimpak',
      'ekwd|HasLegendary_Armor_HealthRegen',
      'ekwd|HasLegendary_Armor_Weightless',
    ],
  },
];
