import { ICON_MELEE_WEAPONS } from '../generated/icons-enum';
import { LeftSignature, RightSignature } from '../utils/const';
import type { Rule } from '../utils/types';

export const MELEE_WEAPONS_RULES: Rule[] = [
  {
    order: 0,
    iconName: ICON_MELEE_WEAPONS.PowerFist,
    leftSignature: LeftSignature.Weapon,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: true,
    isFullReplaced: false,
    header: '0x2312',
    include: ['edid|PowerFist', 'edid|Gauntlet'],
    exclude: [],
  },
  {
    order: 1,
    iconName: ICON_MELEE_WEAPONS.Unarmed,
    leftSignature: LeftSignature.Weapon,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x2313',
    include: ['ekwd|WeaponTypeUnarmed'],
    exclude: ['edid|PowerFist', 'edid|Gauntlet'],
  },
  {
    order: 2,
    iconName: ICON_MELEE_WEAPONS.Chainsaw,
    leftSignature: LeftSignature.Weapon,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x2314',
    include: ['edid|chainsaw'],
    exclude: [],
  },
  {
    order: 3,
    iconName: ICON_MELEE_WEAPONS.Shishkebab,
    leftSignature: LeftSignature.Weapon,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x2315',
    include: ['edid|shishkebab'],
    exclude: [],
  },
  {
    order: 4,
    iconName: ICON_MELEE_WEAPONS.Ripper,
    leftSignature: LeftSignature.Weapon,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x2316',
    include: ['edid|ripper'],
    exclude: [],
  },
  {
    order: 5,
    iconName: ICON_MELEE_WEAPONS.Knife,
    leftSignature: LeftSignature.Weapon,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x2317',
    include: ['edid|knife'],
    exclude: ['edid|Throwing_Knife'],
  },
  {
    order: 6,
    iconName: ICON_MELEE_WEAPONS.Machete,
    leftSignature: LeftSignature.Weapon,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x2318',
    include: ['edid|machete'],
    exclude: [],
  },
  {
    order: 7,
    iconName: ICON_MELEE_WEAPONS.OneHandedAxe,
    leftSignature: LeftSignature.Weapon,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x2319',
    include: ['ekwd|WeaponTypeAxe', 'ekwd|WeaponTypeMelee1H'],
    exclude: [],
  },
  {
    order: 8,
    iconName: ICON_MELEE_WEAPONS.OneHandedBat,
    leftSignature: LeftSignature.Weapon,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x231a',
    include: ['ekwd|WeaponTypeBlunt', 'ekwd|WeaponTypeMelee1H'],
    exclude: [],
  },
  {
    order: 9,
    iconName: ICON_MELEE_WEAPONS.OneHandedMelee,
    leftSignature: LeftSignature.Weapon,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x231b',
    include: ['ekwd|WeaponTypeMelee1H'],
    exclude: [],
  },
  {
    order: 10,
    iconName: ICON_MELEE_WEAPONS.SuperSledge,
    leftSignature: LeftSignature.Weapon,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x231c',
    include: ['edid|SuperSledge'],
    exclude: [],
  },
  {
    order: 11,
    iconName: ICON_MELEE_WEAPONS.TwoHandedBat,
    leftSignature: LeftSignature.Weapon,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x231d',
    include: ['ekwd|WeaponTypeBlunt', 'ekwd|WeaponTypeMelee2H'],
    exclude: [],
  },
  {
    order: 12,
    iconName: ICON_MELEE_WEAPONS.TwoHandedAxe,
    leftSignature: LeftSignature.Weapon,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x231e',
    include: ['ekwd|WeaponTypeAxe', 'ekwd|WeaponTypeMelee2H'],
    exclude: [],
  },
  {
    order: 13,
    iconName: ICON_MELEE_WEAPONS.TwoHandedSword,
    leftSignature: LeftSignature.Weapon,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x231f',
    include: ['ekwd|WeaponTypeSword', 'ekwd|WeaponTypeMelee2H'],
    exclude: [],
  },
  {
    order: 14,
    iconName: ICON_MELEE_WEAPONS.TwoHandedMelee,
    leftSignature: LeftSignature.Weapon,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x2320',
    include: ['ekwd|WeaponTypeMelee2H'],
    exclude: [],
  },
];
