import { ICON_MINES } from '@/generated/icons-enum';
import { LeftSignature, RightSignature } from '@/constants';
import type { Rule } from '@/types';

export const MINES_RULES: Rule<ICON_MINES>[] = [
  {
    order: 0,
    iconName: ICON_MINES.CryoMine,
    leftSignature: LeftSignature.Weapon,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x226f',
    include: ['edid|CryoMine'],
    exclude: [],
  },
  {
    order: 1,
    iconName: ICON_MINES.PlasmaMine,
    leftSignature: LeftSignature.Weapon,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x2270',
    include: ['edid|PlasmaMine'],
    exclude: [],
  },
  {
    order: 2,
    iconName: ICON_MINES.PulseMine,
    leftSignature: LeftSignature.Weapon,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x2271',
    include: ['edid|PulseMine'],
    exclude: [],
  },
  {
    order: 3,
    iconName: ICON_MINES.BottlecapMine,
    leftSignature: LeftSignature.Weapon,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x2272',
    include: ['edid|BottlecapMine'],
    exclude: [],
  },
  {
    order: 4,
    iconName: ICON_MINES.NukeMine,
    leftSignature: LeftSignature.Weapon,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x2273',
    include: ['edid|NukeMine'],
    exclude: [],
  },
  {
    order: 5,
    iconName: ICON_MINES.FragmentationMine,
    leftSignature: LeftSignature.Weapon,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x2274',
    include: ['ekwd|WeaponTypeMine'],
    exclude: [
      'edid|CryoMine',
      'edid|PlasmaMine',
      'edid|PulseMine',
      'edid|BottlecapMine',
      'edid|NukeMine',
    ],
  },
];
