import { ICON_MISC } from '@/generated/icons-enum';
import { LeftSignature, RightSignature } from '@/constants';
import type { Rule } from '@/types';

export const MISC_RULES: Rule[] = [
  {
    order: 0,
    iconName: ICON_MISC.LegendaryModule,
    leftSignature: LeftSignature.Misc,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: true,
    isFullReplaced: false,
    header: '0x2297',
    include: ['edid|miscmod', 'edid|LegendaryModule'],
    exclude: [],
  },
  {
    order: 1,
    iconName: ICON_MISC.LegendaryCore,
    leftSignature: LeftSignature.Currency,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x2298',
    include: ['edid|LegendaryCore'],
    exclude: [],
  },
  {
    order: 2,
    iconName: ICON_MISC.TreasureNote,
    leftSignature: LeftSignature.Misc,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x2299',
    include: ['edid|Treasury_Note'],
    exclude: [],
  },
  {
    order: 3,
    iconName: ICON_MISC.NukeCard,
    leftSignature: LeftSignature.Misc,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x229a',
    include: ['ekwd|ObjectTypeNukeKeycard'],
    exclude: [],
  },
  {
    order: 4,
    iconName: ICON_MISC.RepairKit,
    leftSignature: LeftSignature.Utility,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x229b',
    include: ['edid|RepairKit'],
    exclude: [],
  },
  {
    order: 5,
    iconName: ICON_MISC.Flux,
    leftSignature: LeftSignature.Misc,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x229c',
    include: ['ekwd|ObjectTypeFlux'],
    exclude: [],
  },
  {
    order: 6,
    iconName: ICON_MISC.Token,
    leftSignature: LeftSignature.Misc,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x229d',
    include: ['edid|token'],
    exclude: [],
  },
  {
    order: 7,
    iconName: ICON_MISC.Cards,
    leftSignature: LeftSignature.Misc,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x229e',
    include: ['ekwd|Moon_CryptidCardKeyword'],
    exclude: [],
  },
  {
    order: 8,
    iconName: ICON_MISC.Bulk,
    leftSignature: LeftSignature.Misc,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x229f',
    include: ['edid|Bulk'],
    exclude: [],
  },
  {
    order: 9,
    iconName: ICON_MISC.Components,
    leftSignature: LeftSignature.Misc,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x22a0',
    include: ['ekwd|ObjectTypeComponent'],
    exclude: [],
  },
  {
    order: 10,
    iconName: ICON_MISC.Corpse,
    leftSignature: LeftSignature.Misc,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: true,
    isFullReplaced: false,
    header: '0x22a1',
    include: [
      'edid|Horn_Sheepsquatch',
      'edid|FloaterPusSac',
      'edid|WendigoColossus',
      'edid|RadscorpionStinger',
      'edid|BloatflyGland',
      'edid|AcidGulperGland',
      'edid|MoleRatTeeth',
      'edid|TickBloodSac',
      'edid|DeathclawHand',
      'edid|BloodbugProboscis',
      'edid|SheepsquatchSkull',
      'edid|StingwingBarb',
      'edid|BeaverTeeth',
      'edid|WendigoTeeth',
    ],
    exclude: [],
  },
  {
    order: 11,
    iconName: ICON_MISC.Skull,
    leftSignature: LeftSignature.Misc,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x22a2',
    include: ['ekwd|BoneTypeSkull'],
    exclude: [],
  },
  {
    order: 12,
    iconName: ICON_MISC.Bones,
    leftSignature: LeftSignature.Misc,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x22a3',
    include: ['ekwd|ObjectTypeBones'],
    exclude: ['ekwd|BoneTypeSkull'],
  },
  {
    order: 13,
    iconName: ICON_MISC.TeddyBear,
    leftSignature: LeftSignature.Misc,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x22a4',
    include: ['ekwd|ObjectTypeTeddyBear'],
    exclude: [],
  },
  {
    order: 14,
    iconName: ICON_MISC.RocketToy,
    leftSignature: LeftSignature.Misc,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x22a5',
    include: ['ekwd|ObjectTypeToy'],
    exclude: [],
  },
  {
    order: 15,
    iconName: ICON_MISC.CircuitBoard,
    leftSignature: LeftSignature.Misc,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: true,
    isFullReplaced: false,
    header: '0x22a6',
    include: ['edid|CircuitBoard', 'edid|BiometricScanner', 'edid|EyebotPart'],
    exclude: [],
  },
  {
    order: 16,
    iconName: ICON_MISC.Canister,
    leftSignature: LeftSignature.Misc,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x22a7',
    include: ['edid|canister'],
    exclude: [],
  },
  {
    order: 17,
    iconName: ICON_MISC.MetalScrap,
    leftSignature: LeftSignature.Misc,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: true,
    isFullReplaced: false,
    header: '0x22a8',
    include: [
      'edid|TinCan',
      'edid|PaintCan',
      'edid|OilCan',
      'edid|SetCan',
      'edid|Fork',
    ],
    exclude: [],
  },
  {
    order: 18,
    iconName: ICON_MISC.Ore,
    leftSignature: LeftSignature.Misc,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x22a9',
    include: ['edid|_ore_'],
    exclude: [],
  },
  {
    order: 19,
    iconName: ICON_MISC.Junk,
    leftSignature: LeftSignature.Misc,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x22aa',
    include: [],
    exclude: ['edid|miscmod'],
  },
  {
    order: 20,
    iconName: ICON_MISC.Quest,
    leftSignature: LeftSignature.Misc,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x22ab',
    include: [],
    exclude: [],
  },
];
