import { ICON_RIFLES } from '@/generated/icons-enum';
import { LeftSignature, RightSignature } from '@/constants';
import type { Rule } from '@/types';

export const RIFLES_RULES: Rule<ICON_RIFLES>[] = [
  {
    order: 0,
    iconName: ICON_RIFLES.Fixer,
    leftSignature: LeftSignature.Weapon,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x2332',
    include: ['edid|fixer'],
    exclude: [],
  },
  {
    order: 1,
    iconName: ICON_RIFLES.HandmadeRifle,
    leftSignature: LeftSignature.Weapon,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x2333',
    include: ['edid|HandmadeRifle'],
    exclude: [],
  },
  {
    order: 2,
    iconName: ICON_RIFLES.RailwayRifle,
    leftSignature: LeftSignature.Weapon,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x2334',
    include: ['edid|RailwayRifle'],
    exclude: [],
  },
  {
    order: 3,
    iconName: ICON_RIFLES.TeslaRifle,
    leftSignature: LeftSignature.Weapon,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x2335',
    include: ['edid|LightningGun'],
    exclude: [],
  },
  {
    order: 4,
    iconName: ICON_RIFLES.AlienDisintegrator,
    leftSignature: LeftSignature.Weapon,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x2336',
    include: ['edid|AlienRifle'],
    exclude: [],
  },
  {
    order: 5,
    iconName: ICON_RIFLES.GaussRifle,
    leftSignature: LeftSignature.Weapon,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x2337',
    include: ['edid|GaussRifle'],
    exclude: [],
  },
  {
    order: 6,
    iconName: ICON_RIFLES.PlasmaRifle,
    leftSignature: LeftSignature.Weapon,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x2338',
    include: ['edid|PlasmaGun'],
    exclude: [],
  },
  {
    order: 7,
    iconName: ICON_RIFLES.LaserRifle,
    leftSignature: LeftSignature.Weapon,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x2339',
    include: ['edid|LaserGun'],
    exclude: [],
  },
  {
    order: 8,
    iconName: ICON_RIFLES.PipeRifle,
    leftSignature: LeftSignature.Weapon,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x233a',
    include: ['edid|PipeGun'],
    exclude: [],
  },
  {
    order: 9,
    iconName: ICON_RIFLES.LaserMusket,
    leftSignature: LeftSignature.Weapon,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x233b',
    include: ['edid|LaserMusket'],
    exclude: [],
  },
  {
    order: 10,
    iconName: ICON_RIFLES.Rifle,
    leftSignature: LeftSignature.Weapon,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x233c',
    include: ['ekwd|WeaponTypeRifle'],
    exclude: [
      'edid|fixer',
      'edid|HandmadeRifle',
      'edid|RailwayRifle',
      'edid|LightningGun',
      'edid|AlienRifle',
      'edid|GaussRifle',
      'edid|PlasmaGun',
      'edid|LaserGun',
      'edid|PipeGun',
      'edid|LaserMusket',
      'edid|WesternSpirit',
    ],
  },
];
