import { ICON_WEAPONS } from '@/generated/icons-enum';
import { LeftSignature, RightSignature } from '@/constants';
import type { Rule } from '@/types';

export const WEAPONS_RULES: Rule[] = [
  {
    order: 0,
    iconName: ICON_WEAPONS.UniqueWeapon,
    leftSignature: LeftSignature.InstanceNamingRules,
    rightSignature: RightSignature.WNAM,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x230a',
    include: ['ekwd|CustomItemName'],
    exclude: [],
  },
  {
    order: 1,
    iconName: ICON_WEAPONS.Binoculars,
    leftSignature: LeftSignature.Weapon,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x230b',
    include: ['edid|binoculars'],
    exclude: [],
  },
  {
    order: 2,
    iconName: ICON_WEAPONS.Camera,
    leftSignature: LeftSignature.Weapon,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x230c',
    include: ['edid|camera'],
    exclude: [],
  },
  {
    order: 3,
    iconName: ICON_WEAPONS.AssaultronHead,
    leftSignature: LeftSignature.Weapon,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x230d',
    include: ['edid|AssaultronHead'],
    exclude: [],
  },
  {
    order: 4,
    iconName: ICON_WEAPONS.Syringer,
    leftSignature: LeftSignature.Weapon,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x230e',
    include: ['edid|syringer'],
    exclude: [],
  },
  {
    order: 5,
    iconName: ICON_WEAPONS.Bow,
    leftSignature: LeftSignature.Weapon,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x230f',
    include: ['edid|bow'],
    exclude: ['edid|CompoundBow', 'edid|Bowie', 'edid|crossbow'],
  },
  {
    order: 6,
    iconName: ICON_WEAPONS.CompoundBow,
    leftSignature: LeftSignature.Weapon,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: false,
    isFullReplaced: false,
    header: '0x2310',
    include: ['edid|CompoundBow'],
    exclude: [],
  },
  {
    order: 7,
    iconName: ICON_WEAPONS.Weapon,
    leftSignature: LeftSignature.Weapon,
    rightSignature: RightSignature.FULL,
    isInjected: false,
    isDeleted: false,
    isAnyKeyword: false,
    isInclusiveOr: true,
    isFullReplaced: false,
    header: '0x2311',
    include: ['edid|10mm', 'edid|crossbow'],
    exclude: [],
  },
];
